### ISSUE TITLE
Extension name is cryptic.

### ISSUE THREAD

**Issue by mtomasz-chromium** [yoichiro/chromeos-filesystem-cifs#10]
For a typical user it may be very difficult to understand what "SMB/CIFS File System" means. I'd suggest something simpler if you want your extension to be popular. I guess that most users will just want to access their files on Windows without caring about the underlying protocol. But this is just a suggestion.

**Comment by yoichiro** [comment]
@mtomasz-chromium Actually... I also think it, too... But, I was not able to think a good name...

**Comment by yoichiro** [comment]
@mtomasz-chromium My ideas are below. Which is your favorite?
- File System for Windows(TM)
- File System for Samba
- Samba File System
- SMB File System
- File System for SMB/CIFS
- File System for SMB
- File System for Windows(TM) Shared Files
- Windows(TM) File System

Hmm... To decide name is always difficult...

**Comment by mtomasz-chromium** [comment]
In my opinion Samba, SMB, CIFS are cryptic and less than few percents of Chromebook users will understand them. I'd vote for the last one.

Also, this document may explain how to use Windows in the app name.
https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/general.aspx

**Comment by yoichiro** [comment]
Hmm... I intend to apply this name "Windows® File System". Also, icon images will be changed.

**Comment by mtomasz-chromium** [comment]
Hm, I think according to the link Windows(R) can't be at the beginning. I'd recommend to check carefully.

**Comment by yoichiro** [comment]
Oh, really? Hmm... OK, I read the guideline more carefully...

**Comment by divx118** [comment]
Hmm why is samba/smb/cifs cryptic. I don't use windows at all, however I am using smb shares on my linux machines. Windows would be cryptic to me. I would at least leave some reference to "smb" in there.
However just my 2 cents. I am already glad you started the app and even more nice shared the source.

**Comment by ghost** [comment]
I think the name is fine. Those who need it will know those terms. The fact that Windows file share is mentioned in the description will allow it to be found in more general searches.

**Comment by mtomasz-chromium** [comment]
Hm. It seems that this extension is used often for NAS. If so, then maybe the current name is not bad? On the other hand, maybe we can include both, like "File System for SMB/CIFS and Windows(R)"? But I don't want to suggest. It's up to you, your extension :).

**Comment by AndreyLavrov** [comment]
I think that the name is good.
After this application will work stable then the next one app might have a "DFS" name for connecting real enterprise folders on a File Service cluster that is powered by Windows Servers through domain account from Active Directory.

**Comment by yoichiro** [comment]
Probably, the Domain Authentication can be supported at the next version. Thus, I intend to change the name to "File System for SMB/CIFS and Windows(R)"...

**Comment by yoichiro** [comment]
I have just released the new version 1.2.0. At the version, I changed the name to "File System for SMB/CIFS and Windows(R)". Thank you for commenting nice advices! I close this issue.
