### ISSUE TITLE
Chromebook flip 

### ISSUE THREAD

**Issue by iondisrupter** [yoichiro/chromeos-filesystem-cifs#105]
Was working two days ago.
now I get this...
This application is not supported on this computer. Installation has been disabled. The following problems are detected:
Chrome of version at least 45 is required

Chromebook Flip Asus
Version 44.0.2403.156
Platform 7077.134.0 (Official Build) stable-channel veyron_minnie
Firmware Google_Veyron_Minnie.6588.95.0

**Comment by yoichiro** [comment]
@iondisrupter See the duplicated issue #110.
