### ISSUE TITLE
NT_STATUS_OBJECT PATH NOT FOUND Problem

### ISSUE THREAD

**Issue by tyw7** [yoichiro/chromeos-filesystem-cifs#107]
I have a problem with MyCloud.  It previously worked in the past but not any longer.

Looked up with chrome.mdns:  Array[0]
Domain name not specified. '?' will be applied.
connect
Header
NegotiateProtocolRequest
Packet
Negotiated with SMB2
Header
NegotiateResponse
Header
SessionSetupRequest
Packet
Header
NTLMSSP_NEGOTIATE_UNICODE: true
NTLMSSP_NEGOTIATE_OEM: false
NTLMSSP_REQUEST_TARGET: true
NTLMSSP_NEGOTIATE_SIGN: false
NTLMSSP_NEGOTIATE_SEAL: false
NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
NTLMSSP_NEGOTIATE_LM_KEY: false
NTLMSSP_NEGOTIATE_NETWARE: false
NTLMSSP_NEGOTIATE_NTLM: true
NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
NTLMSSP_NEGOTIATE_LOCAL_CALL: false
NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
NTLMSSP_TARGET_TYPE_DOMAIN: false
NTLMSSP_TARGET_TYPE_SERVER: true
NTLMSSP_TARGET_TYPE_SHARE: false
NTLMSSP_NEGOTIATE_NTLM2: true
NTLMSSP_REQUEST_INIT_RESPONSE: false
NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
NTLMSSP_NEGOTIATE_TARGET_INFO: true
NTLMSSP_NEGOTIATE_128: true
NTLMSSP_NEGOTIATE_KEY_EXCH: false
NTLMSSP_NEGOTIATE_56: false
Header
SessionSetupRequest
Packet
Header
TreeConnectRequest
Packet
Header
TreeConnectResponse
Header
CreateRequest
Packet
c0000034: NT_STATUS_OBJECT_NAME_NOT_FOUND
Domain name not specified. '?' will be applied.
connect
Header
NegotiateProtocolRequest
Packet
Negotiated with SMB2
Header
NegotiateResponse
Header
SessionSetupRequest
Packet
Header
NTLMSSP_NEGOTIATE_UNICODE: true
NTLMSSP_NEGOTIATE_OEM: false
NTLMSSP_REQUEST_TARGET: true
NTLMSSP_NEGOTIATE_SIGN: false
NTLMSSP_NEGOTIATE_SEAL: false
NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
NTLMSSP_NEGOTIATE_LM_KEY: false
NTLMSSP_NEGOTIATE_NETWARE: false
NTLMSSP_NEGOTIATE_NTLM: true
NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
NTLMSSP_NEGOTIATE_LOCAL_CALL: false
NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
NTLMSSP_TARGET_TYPE_DOMAIN: false
NTLMSSP_TARGET_TYPE_SERVER: true
NTLMSSP_TARGET_TYPE_SHARE: false
NTLMSSP_NEGOTIATE_NTLM2: true
NTLMSSP_REQUEST_INIT_RESPONSE: false
NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
NTLMSSP_NEGOTIATE_TARGET_INFO: true
NTLMSSP_NEGOTIATE_128: true
NTLMSSP_NEGOTIATE_KEY_EXCH: false
NTLMSSP_NEGOTIATE_56: false
Header
SessionSetupRequest
Packet
Header
TreeConnectRequest
Packet
Header
TreeConnectResponse
Header
CreateRequest
Packet
c0000034: NT_STATUS_OBJECT_NAME_NOT_FOUND
Domain name not specified. '?' will be applied.
connect
Header
NegotiateProtocolRequest
Packet
Negotiated with SMB2
Header
NegotiateResponse
Header
SessionSetupRequest
Packet
Header
NTLMSSP_NEGOTIATE_UNICODE: true
NTLMSSP_NEGOTIATE_OEM: false
NTLMSSP_REQUEST_TARGET: true
NTLMSSP_NEGOTIATE_SIGN: false
NTLMSSP_NEGOTIATE_SEAL: false
NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
NTLMSSP_NEGOTIATE_LM_KEY: false
NTLMSSP_NEGOTIATE_NETWARE: false
NTLMSSP_NEGOTIATE_NTLM: true
NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
NTLMSSP_NEGOTIATE_LOCAL_CALL: false
NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
NTLMSSP_TARGET_TYPE_DOMAIN: false
NTLMSSP_TARGET_TYPE_SERVER: true
NTLMSSP_TARGET_TYPE_SHARE: false
NTLMSSP_NEGOTIATE_NTLM2: true
NTLMSSP_REQUEST_INIT_RESPONSE: false
NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
NTLMSSP_NEGOTIATE_TARGET_INFO: true
NTLMSSP_NEGOTIATE_128: true
NTLMSSP_NEGOTIATE_KEY_EXCH: false
NTLMSSP_NEGOTIATE_56: false
Header
SessionSetupRequest
Packet
Header
TreeConnectRequest
Packet
Header
TreeConnectResponse
Header
CreateRequest
Packet
c0000034: NT_STATUS_OBJECT_NAME_NOT_FOUND
Domain name not specified. '?' will be applied.
connect
Header
NegotiateProtocolRequest
Packet
Negotiated with SMB2
Header
NegotiateResponse
Header
SessionSetupRequest
Packet
Header
NTLMSSP_NEGOTIATE_UNICODE: true
NTLMSSP_NEGOTIATE_OEM: false
NTLMSSP_REQUEST_TARGET: true
NTLMSSP_NEGOTIATE_SIGN: false
NTLMSSP_NEGOTIATE_SEAL: false
NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
NTLMSSP_NEGOTIATE_LM_KEY: false
NTLMSSP_NEGOTIATE_NETWARE: false
NTLMSSP_NEGOTIATE_NTLM: true
NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
NTLMSSP_NEGOTIATE_LOCAL_CALL: false
NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
NTLMSSP_TARGET_TYPE_DOMAIN: false
NTLMSSP_TARGET_TYPE_SERVER: true
NTLMSSP_TARGET_TYPE_SHARE: false
NTLMSSP_NEGOTIATE_NTLM2: true
NTLMSSP_REQUEST_INIT_RESPONSE: false
NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
NTLMSSP_NEGOTIATE_TARGET_INFO: true
NTLMSSP_NEGOTIATE_128: true
NTLMSSP_NEGOTIATE_KEY_EXCH: false
NTLMSSP_NEGOTIATE_56: false
Header
SessionSetupRequest
Packet
Header
TreeConnectRequest
Packet
Header
TreeConnectResponse
Header
CreateRequest
Packet
c0000034: NT_STATUS_OBJECT_NAME_NOT_FOUND
Domain name not specified. '?' will be applied.
connect
Header
NegotiateProtocolRequest
Packet
Negotiated with SMB2
Header
NegotiateResponse
Header
SessionSetupRequest
Packet
Header
NTLMSSP_NEGOTIATE_UNICODE: true
NTLMSSP_NEGOTIATE_OEM: false
NTLMSSP_REQUEST_TARGET: true
NTLMSSP_NEGOTIATE_SIGN: false
NTLMSSP_NEGOTIATE_SEAL: false
NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
NTLMSSP_NEGOTIATE_LM_KEY: false
NTLMSSP_NEGOTIATE_NETWARE: false
NTLMSSP_NEGOTIATE_NTLM: true
NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
NTLMSSP_NEGOTIATE_LOCAL_CALL: false
NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
NTLMSSP_TARGET_TYPE_DOMAIN: false
NTLMSSP_TARGET_TYPE_SERVER: true
NTLMSSP_TARGET_TYPE_SHARE: false
NTLMSSP_NEGOTIATE_NTLM2: true
NTLMSSP_REQUEST_INIT_RESPONSE: false
NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
NTLMSSP_NEGOTIATE_TARGET_INFO: true
NTLMSSP_NEGOTIATE_128: true
NTLMSSP_NEGOTIATE_KEY_EXCH: false
NTLMSSP_NEGOTIATE_56: false
Header
SessionSetupRequest
Packet
Header
TreeConnectRequest
Packet
Header
TreeConnectResponse
Header
CreateRequest
Packet
c0000034: NT_STATUS_OBJECT_NAME_NOT_FOUND
Domain name not specified. '?' will be applied.
connect
Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
NegotiateProtocolRequest {types_: Types, dialects: Array[0], dialects_: Array[2]}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 58, packetHelper_: PacketHelper}
Negotiated with SMB2
Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 0, channelSequence_: 0…}
NegotiateResponse {types_: Types, structureSize_: 65, securityMode_: 1, dialectRevision_: 514, serverGuid_: "wdmycloud"…}
Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}
SessionSetupRequest {types_: Types, flags_: 0, securityMode_: 1, capabilities_: 1, channel_: 0…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 129, packetHelper_: PacketHelper}
Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 22…}
NTLMSSP_NEGOTIATE_UNICODE: true
NTLMSSP_NEGOTIATE_OEM: false
NTLMSSP_REQUEST_TARGET: true
NTLMSSP_NEGOTIATE_SIGN: false
NTLMSSP_NEGOTIATE_SEAL: false
NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
NTLMSSP_NEGOTIATE_LM_KEY: false
NTLMSSP_NEGOTIATE_NETWARE: false
NTLMSSP_NEGOTIATE_NTLM: true
NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
NTLMSSP_NEGOTIATE_LOCAL_CALL: false
NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
NTLMSSP_TARGET_TYPE_DOMAIN: false
NTLMSSP_TARGET_TYPE_SERVER: true
NTLMSSP_TARGET_TYPE_SHARE: false
NTLMSSP_NEGOTIATE_NTLM2: true
NTLMSSP_REQUEST_INIT_RESPONSE: false
NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
NTLMSSP_NEGOTIATE_TARGET_INFO: true
NTLMSSP_NEGOTIATE_128: true
NTLMSSP_NEGOTIATE_KEY_EXCH: false
NTLMSSP_NEGOTIATE_56: false
Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}
SessionSetupRequest {types_: Types, flags_: 0, securityMode_: 1, capabilities_: 1, channel_: 0…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 314, packetHelper_: PacketHelper}
Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}
TreeConnectRequest {types_: Types, path_: "\192.168.0.16\IPC$"}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 110, packetHelper_: PacketHelper}
Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}chainOffset_: 0channelSequence_: 0command_: 3creditCharge_: 1creditsGranted_: 1creditsRequested_: 1flags_: 1messageId_: 3processId_: 6protocol_: "SMB"sessionId_: 3770046638signature_: Uint8Array[16]status_: 0structureSize_: 64treeId_: 2356449063types_: Types__proto__: Headerconstructor: ()createArrayBuffer: ()getChainOffset: ()getChannelSequence: ()getCommand: ()getCreditCharge: ()getCreditsGranted: ()getCreditsRequested: ()getFlags: ()getMessageId: ()getProcessId: ()getProtocol: ()getSessionId: ()getSignature: ()getStatus: ()getStructureSize: ()getTreeId: ()isFlagsOf: (field)load: (packet)setChainOffset: (chainOffset)setChannelSequence: (channelSequence)setCommand: (command)setCreditCharge: (creditCharge)setCreditsGranted: (creditsGranted)setCreditsRequested: (creditsRequested)setFlags: (flags)setMessageId: (messageId)setProcessId: (processId)setProtocol: (protocol)setSessionId: (sessionId)setSignature: (signature)setStatus: (status)setStructureSize: (structureSize)setTreeId: (treeId)**proto**: Object
TreeConnectResponse {types_: Types, structureSize_: 16, shareType_: 2, shareFlags_: 0, capabilities_: 0…}
Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}chainOffset_: 0channelSequence_: 0command_: 5creditCharge_: 1creditsGranted_: 0creditsRequested_: 1flags_: 0messageId_: 4processId_: 6protocol_: "SMB"sessionId_: 3770046638signature_: 0status_: 0structureSize_: 64treeId_: 2356449063types_: Types__proto__: Header
CreateRequest {types_: Types, structureSize_: 57, requestedOplockLevel_: 0, impersonationLevel_: 2, desiredAccess_: -1073741824…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 160, packetHelper_: PacketHelper}
c0000034: NT_STATUS_OBJECT_NAME_NOT_FOUND
Domain name not specified. '?' will be applied.
connect
Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
NegotiateProtocolRequest {types_: Types, dialects: Array[0], dialects_: Array[2]}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 58, packetHelper_: PacketHelper}
Negotiated with SMB2
Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 0, channelSequence_: 0…}
NegotiateResponse {types_: Types, structureSize_: 65, securityMode_: 1, dialectRevision_: 514, serverGuid_: "wdmycloud"…}
Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}
SessionSetupRequest {types_: Types, flags_: 0, securityMode_: 1, capabilities_: 1, channel_: 0…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 129, packetHelper_: PacketHelper}
Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 22…}
NTLMSSP_NEGOTIATE_UNICODE: true
NTLMSSP_NEGOTIATE_OEM: false
NTLMSSP_REQUEST_TARGET: true
NTLMSSP_NEGOTIATE_SIGN: false
NTLMSSP_NEGOTIATE_SEAL: false
NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
NTLMSSP_NEGOTIATE_LM_KEY: false
NTLMSSP_NEGOTIATE_NETWARE: false
NTLMSSP_NEGOTIATE_NTLM: true
NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
NTLMSSP_NEGOTIATE_LOCAL_CALL: false
NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
NTLMSSP_TARGET_TYPE_DOMAIN: false
NTLMSSP_TARGET_TYPE_SERVER: true
NTLMSSP_TARGET_TYPE_SHARE: false
NTLMSSP_NEGOTIATE_NTLM2: true
NTLMSSP_REQUEST_INIT_RESPONSE: false
NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
NTLMSSP_NEGOTIATE_TARGET_INFO: true
NTLMSSP_NEGOTIATE_128: true
NTLMSSP_NEGOTIATE_KEY_EXCH: false
NTLMSSP_NEGOTIATE_56: false
Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}
SessionSetupRequest {types_: Types, flags_: 0, securityMode_: 1, capabilities_: 1, channel_: 0…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 314, packetHelper_: PacketHelper}
Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}
TreeConnectRequest {types_: Types, path_: "\192.168.0.16\IPC$"}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 110, packetHelper_: PacketHelper}
Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}
TreeConnectResponse {types_: Types, structureSize_: 16, shareType_: 2, shareFlags_: 0, capabilities_: 0…}
Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}
CreateRequest {types_: Types, structureSize_: 57, requestedOplockLevel_: 0, impersonationLevel_: 2, desiredAccess_: -1073741824…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 160, packetHelper_: PacketHelper}
c0000034: NT_STATUS_OBJECT_NAME_NOT_FOUND

**Comment by yoichiro** [comment]
@tyw7 I just released a new version 2.1.1. The previous version included a bug which a wrong path specified (\srvsvc). I guess that you can access to your server with the latest version. It would be great if you can do test again.

**Comment by tyw7** [comment]
I was able to access by switching to SMB1.

Edit: Either SMB works.  Any difference?

**Comment by yoichiro** [comment]
@tyw7 I close this issue, because your feedback looks good. SMB1 and SMB2 are so different protocols.
