### ISSUE TITLE
Help connecting home NAS

### ISSUE THREAD

**Issue by KevinTho** [yoichiro/chromeos-filesystem-cifs#109]
I would be very grateful for some guidance since I don't seem to be able to get it working. I am trying to access a drive on my NAS Box (iomega iConnect) The name of the NAS is storage-105. It has a drive attached to it called TOURO_MOBILE. There is no password protection on it. When adding the drive as a network drive in windows I use the \storage-105\TOURO_MOBILE as the drive name. What do I enter here ? I have tried putting storage-105 into the Server Host Name / IP Address field, and also the IP address of the NAS. I left User Name and password blank. I left Domain blank. I put TOURO_MOBILE into the shared resource name. I get NT_STATUS_ACCESS_DENIED when I try to mount. I have tried lots of other combinations, but always seem to get access denied. I also tried using the network search option, but there is nothing to select. This network drive can be access using my windows machine, my linux box, and my android phone, as well as my networked PVR. I am using a new ASUS Chromebook flip, using the Chrome OS beta-channel. Any help would be really appreciated.

**Comment by yoichiro** [comment]
@KevinTho It would be great if you can post the debug log by the following steps:
https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by KevinTho** [comment]
Here is the log as requested, thanks.

Domain name not specified. '?' will be applied.
background.js:6395 Negotiated with SMB1/CIFS
background.js:6395 CAP_EXTENDED_SECURITY: true
background.js:6395 CAP_COMPRESSED_DATA: false
background.js:6395 CAP_BULK_TRANSFER: false
background.js:6395 CAP_UNIX: true
background.js:6395 CAP_LARGE_WRITEX: true
background.js:6395 CAP_LARGE_READX: true
background.js:6395 CAP_INFOLEVEL_PASSTHROUGH: true
background.js:6395 CAP_DFS: true
background.js:6395 CAP_NT_FIND: true
background.js:6395 CAP_LOCK_AND_READ: true
background.js:6395 CAP_LEVEL_II_OPLOCKS: true
background.js:6395 CAP_STATUS32: true
background.js:6395 CAP_RPC_REMOTE_APIS: true
background.js:6395 CAP_NT_SMBS: true
background.js:6395 CAP_LARGE_FILES: true
background.js:6395 CAP_UNICODE: true
background.js:6395 CAP_MPX_MODE: false
background.js:6395 CAP_RAW_MODE: true
background.js:6395 NEGOTIATE_SECURITY_SIGNATURES_REQUIRED: 0
background.js:6395 NEGOTIATE_SECURITY_SIGNATURES_ENABLED: 0
background.js:6395 NEGOTIATE_SECURITY_CHALLENGE_RESPONSE: 1
background.js:6395 NEGOTIATE_SECURITY_USER_LEVEL: 1
background.js:6395 NTLMSSP_NEGOTIATE_UNICODE: true
background.js:6395 NTLMSSP_NEGOTIATE_OEM: false
background.js:6395 NTLMSSP_REQUEST_TARGET: true
background.js:6395 NTLMSSP_NEGOTIATE_SIGN: false
background.js:6395 NTLMSSP_NEGOTIATE_SEAL: false
background.js:6395 NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
background.js:6395 NTLMSSP_NEGOTIATE_LM_KEY: false
background.js:6395 NTLMSSP_NEGOTIATE_NETWARE: false
background.js:6395 NTLMSSP_NEGOTIATE_NTLM: true
background.js:6395 NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
background.js:6395 NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
background.js:6395 NTLMSSP_NEGOTIATE_LOCAL_CALL: false
background.js:6395 NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
background.js:6395 NTLMSSP_TARGET_TYPE_DOMAIN: false
background.js:6395 NTLMSSP_TARGET_TYPE_SERVER: true
background.js:6395 NTLMSSP_TARGET_TYPE_SHARE: false
background.js:6395 NTLMSSP_NEGOTIATE_NTLM2: true
background.js:6395 NTLMSSP_REQUEST_INIT_RESPONSE: false
background.js:6395 NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
background.js:6395 NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
background.js:6395 NTLMSSP_NEGOTIATE_TARGET_INFO: true
background.js:6395 NTLMSSP_NEGOTIATE_128: true
background.js:6395 NTLMSSP_NEGOTIATE_KEY_EXCH: false
background.js:6395 NTLMSSP_NEGOTIATE_56: false

**Comment by yoichiro** [comment]
@KevinTho You can change the debug log level by clicking the gear icon. The log above didn't have any valuable information to fix your issue.

**Comment by KevinTho** [comment]
new log with trace turned on, hope it helps. Thank you very much for your help, really appreciate it !

Object {serverName: "192.168.0.9", serverPort: "445", username: "", password: "", domainName: ""…}domainName: ""password: ""serverName: "192.168.0.9"serverPort: "445"sharedResource: "TOURO_MOBILE"type: "mount"username: ""**proto**: Object
background.js:6381 Client#login
background.js:6395 Domain name not specified. '?' will be applied.
background.js:6388 connect
background.js:6388 Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}command_: 114errorClass_: 0errorCode_: 0flag2_: 51203flag_: 24multiplexId_: 1ntStyleErrorCode_: 0processId_: 2protocol_: "SMB"treeId_: 0types_: TypesbinaryUtils: BinaryUtilsencoding_: "utf-8"**proto**: BinaryUtilsarrayBufferToString: (buf)arguments: (...)caller: (...)length: 1name: ""prototype: BinaryUtils.arrayBufferToString__proto__: ()<function scope>concatBuffers: (buffers)constructor: ()createUint8Array: (length)stringToArrayBuffer: (str)**proto**: Object__proto__: TypesuserId_: 0__proto__: Header
background.js:6388 NegotiateProtocolRequest {types_: Types, dialects: Array[0], dialects_: Array[2]}
background.js:6388 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 58, packetHelper_: PacketHelper}
background.js:6381 writePacket
background.js:6388 FF53 4D42 7200 0000 0018 03C8 0000 0000  .SMBr...........
0000 0000 0000 0000 0000 0200 0000 0100  ................
0017 0002 4E54 204C 4D20 302E 3132 0002  ....NT LM 0.12..
534D 4220 322E 3030 3200  SMB 2.002.

background.js:6381 readPacket
background.js:6381 _readPacketSize
background.js:6381 _readPacketSize - 2
background.js:6381 readPacket: 127
background.js:6388 FF53 4D42 7200 0000 0088 01C8 0000 0000  .SMBr...........
0000 0000 0000 0000 0000 0200 0000 0100  ................
1100 0003 3200 0100 0441 0000 0000 0100  ....2....A......
3757 0000 FDF3 8080 00F7 387B C7F6 D001  7W........8{....
A8FD 003A 0073 746F 7261 6765 2D31 3035  ...:.storage-105
0000 0000 0060 2806 062B 0601 0505 02A0  .....`(..+......
1E30 1CA0 0E30 0C06 0A2B 0601 0401 8237  .0...0...+.....7
0202 0AA3 0A30 08A0 061B 044E 4F4E 45 .....0.....NONE

background.js:6395 Negotiated with SMB1/CIFS
background.js:6395 CAP_EXTENDED_SECURITY: true
background.js:6395 CAP_COMPRESSED_DATA: false
background.js:6395 CAP_BULK_TRANSFER: false
background.js:6395 CAP_UNIX: true
background.js:6395 CAP_LARGE_WRITEX: true
background.js:6395 CAP_LARGE_READX: true
background.js:6395 CAP_INFOLEVEL_PASSTHROUGH: true
background.js:6395 CAP_DFS: true
background.js:6395 CAP_NT_FIND: true
background.js:6395 CAP_LOCK_AND_READ: true
background.js:6395 CAP_LEVEL_II_OPLOCKS: true
background.js:6395 CAP_STATUS32: true
background.js:6395 CAP_RPC_REMOTE_APIS: true
background.js:6395 CAP_NT_SMBS: true
background.js:6395 CAP_LARGE_FILES: true
background.js:6395 CAP_UNICODE: true
background.js:6395 CAP_MPX_MODE: false
background.js:6395 CAP_RAW_MODE: true
background.js:6395 NEGOTIATE_SECURITY_SIGNATURES_REQUIRED: 0
background.js:6395 NEGOTIATE_SECURITY_SIGNATURES_ENABLED: 0
background.js:6395 NEGOTIATE_SECURITY_CHALLENGE_RESPONSE: 1
background.js:6395 NEGOTIATE_SECURITY_USER_LEVEL: 1
background.js:6388 Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
background.js:6388 NegotiateProtocolResponse {types_: Types, dialectIndex_: 0, securityMode_: 3, maxMpxCount_: 50, maxNumberVCs_: 1…}
background.js:6388 Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 0, errorCode_: 0…}
background.js:6388 SessionSetupAndxRequest {types_: Types, maxBufferSize_: 16644, maxMpxCount_: 50, vcNumber_: 1, sessionKey_: 22327…}
background.js:6388 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 160, packetHelper_: PacketHelper}
background.js:6381 writePacket
background.js:6388 FF53 4D42 7300 0000 0018 03C8 0000 0000  .SMBs...........
0000 0000 0000 0000 0000 0200 0000 0200  ................
0CFF 0000 0004 4132 0001 0037 5700 0029  ......A2...7W..)
0000 0000 0054 0000 8065 004E 544C 4D53  .....T...e.NTLMS
5350 0001 0000 0005 3208 2001 0001 0020  SP......2. .... 
0000 0008 0008 0021 0000 003F 4653 505F  .......!...?FSP_
4349 4653 4300 6800 7200 6F00 6D00 6500  CIFSC.h.r.o.m.e.
4F00 5300 0000 4600 6900 6C00 6500 2000  O.S...F.i.l.e. .
5300 7900 7300 7400 6500 6D00 2000 6600  S.y.s.t.e.m. .f.
6F00 7200 2000 4300 4900 4600 5300 0000  o.r. .C.I.F.S...

background.js:6381 readPacket
background.js:6381 _readPacketSize
background.js:6381 _readPacketSize - 2
background.js:6381 readPacket: 256
background.js:6388 FF53 4D42 7316 0000 C088 01C8 0000 0000  .SMBs...........
0000 0000 0000 0000 0000 0200 6400 0200  ............d...
04FF 0000 0000 009C 00D5 004E 544C 4D53  ...........NTLMS
5350 0002 0000 0016 0016 0030 0000 0005  SP.........0....
028A 2084 FA14 B58B 6079 0E00 0000 0000  .. .....`y......
0000 0056 0056 0046 0000 0053 0054 004F  ...V.V.F...S.T.O
0052 0041 0047 0045 002D 0031 0030 0035  .R.A.G.E.-.1.0.5
0002 0016 0053 0054 004F 0052 0041 0047  .....S.T.O.R.A.G
0045 002D 0031 0030 0035 0001 0016 0053  .E.-.1.0.5.....S
0054 004F 0052 0041 0047 0045 002D 0031  .T.O.R.A.G.E.-.1
0030 0035 0004 0000 0003 0016 0073 0074  .0.5.........s.t
006F 0072 0061 0067 0065 002D 0031 0030  .o.r.a.g.e.-.1.0
0035 0000 0000 0000 5500 6E00 6900 7800  .5......U.n.i.x.
0000 5300 6100 6D00 6200 6100 2000 3300  ..S.a.m.b.a. .3.
2E00 3000 2E00 3300 3200 0000 5700 4F00  ..0...3.2...W.O.
5200 4B00 4700 5200 4F00 5500 5000 0000  R.K.G.R.O.U.P...

background.js:6388 Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 22, errorCode_: 49152…}
background.js:6395 NTLMSSP_NEGOTIATE_UNICODE: true
background.js:6395 NTLMSSP_NEGOTIATE_OEM: false
background.js:6395 NTLMSSP_REQUEST_TARGET: true
background.js:6395 NTLMSSP_NEGOTIATE_SIGN: false
background.js:6395 NTLMSSP_NEGOTIATE_SEAL: false
background.js:6395 NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
background.js:6395 NTLMSSP_NEGOTIATE_LM_KEY: false
background.js:6395 NTLMSSP_NEGOTIATE_NETWARE: false
background.js:6395 NTLMSSP_NEGOTIATE_NTLM: true
background.js:6395 NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
background.js:6395 NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
background.js:6395 NTLMSSP_NEGOTIATE_LOCAL_CALL: false
background.js:6395 NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
background.js:6395 NTLMSSP_TARGET_TYPE_DOMAIN: false
background.js:6395 NTLMSSP_TARGET_TYPE_SERVER: true
background.js:6395 NTLMSSP_TARGET_TYPE_SHARE: false
background.js:6395 NTLMSSP_NEGOTIATE_NTLM2: true
background.js:6395 NTLMSSP_REQUEST_INIT_RESPONSE: false
background.js:6395 NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
background.js:6395 NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
background.js:6395 NTLMSSP_NEGOTIATE_TARGET_INFO: true
background.js:6395 NTLMSSP_NEGOTIATE_128: true
background.js:6395 NTLMSSP_NEGOTIATE_KEY_EXCH: false
background.js:6395 NTLMSSP_NEGOTIATE_56: false
background.js:6388 Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 0, errorCode_: 0…}
background.js:6388 SessionSetupAndxRequest {types_: Types, maxBufferSize_: 16644, maxMpxCount_: 50, vcNumber_: 1, sessionKey_: 22327…}
background.js:6388 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 360, packetHelper_: PacketHelper}
background.js:6381 writePacket
background.js:6388 FF53 4D42 7300 0000 0018 03C8 0000 0000  .SMBs...........
0000 0000 0000 0000 0000 0200 6400 0300  ............d...
0CFF 0000 0004 4132 0001 0037 5700 00F0  ......A2...7W...
0000 0000 0054 0000 802D 014E 544C 4D53  .....T...-.NTLMS
5350 0003 0000 0018 0018 0040 0000 0086  SP.........@....
0086 0058 0000 0002 0002 00DE 0000 0000  ...X............
0000 00E0 0000 0010 0010 00E0 0000 0000  ................
0000 0000 0000 0001 0008 000D E62C B7C7  .............,..
0D30 E67C B19C 6DF7 5B54 CBBB 225E FE06  .0.|..m.[T.."^..
EEA1 AE29 2BB9 B370 B20A BC98 31D4 5DFB  ...)+..p....1.].
FF47 2601 0100 0000 0000 0080 1392 7BC7  .G&...........{.
F6D0 0112 3414 E368 0200 0000 0000 0002  ....4..h........
0016 0053 0054 004F 0052 0041 0047 0045  ...S.T.O.R.A.G.E
002D 0031 0030 0035 0001 0016 0053 0054  .-.1.0.5.....S.T
004F 0052 0041 0047 0045 002D 0031 0030  .O.R.A.G.E.-.1.0
0035 0004 0000 0003 0016 0073 0074 006F  .5.........s.t.o
0072 0061 0067 0065 002D 0031 0030 0035  .r.a.g.e.-.1.0.5
0000 0000 0000 0000 003F 0046 0053 0050  .........?.F.S.P
005F 0043 0049 0046 0053 0000 4300 6800  ._.C.I.F.S..C.h.
7200 6F00 6D00 6500 4F00 5300 0000 4600  r.o.m.e.O.S...F.
6900 6C00 6500 2000 5300 7900 7300 7400  i.l.e. .S.y.s.t.
6500 6D00 2000 6600 6F00 7200 2000 4300  e.m. .f.o.r. .C.
4900 4600 5300 0000  I.F.S...

background.js:6381 readPacket
background.js:6381 _readPacketSize
background.js:6381 _readPacketSize - 2
background.js:6381 readPacket: 100
background.js:6388 FF53 4D42 7300 0000 0088 01C8 0000 0000  .SMBs...........
0000 0000 0000 0000 0000 0200 6500 0300  ............e...
04FF 0000 0000 0000 0039 0000 5500 6E00  .........9..U.n.
6900 7800 0000 5300 6100 6D00 6200 6100  i.x...S.a.m.b.a.
2000 3300 2E00 3000 2E00 3300 3200 0000   .3...0...3.2...
5700 4F00 5200 4B00 4700 5200 4F00 5500  W.O.R.K.G.R.O.U.
5000 0000  P...

background.js:6381 Client#connectSharedResource
background.js:6388 Header {types_: Types, protocol_: "SMB", command_: 117, errorClass_: 0, errorCode_: 0…}
background.js:6388 TreeConnectAndxRequest {types_: Types, path_: "\192.168.0.9\TOURO_MOBILE", service_: "?????"}
background.js:6388 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 104, packetHelper_: PacketHelper}
background.js:6381 writePacket
background.js:6388 FF53 4D42 7500 0000 0018 03C8 0000 0000  .SMBu...........
0000 0000 0000 0000 0000 0200 6400 0400  ............d...
04FF 0000 0000 0001 003D 0000 5C00 5C00  .........=....
3100 3900 3200 2E00 3100 3600 3800 2E00  1.9.2...1.6.8...
3000 2E00 3900 5C00 5400 4F00 5500 5200  0...9..T.O.U.R.
4F00 5F00 4D00 4F00 4200 4900 4C00 4500  O._.M.O.B.I.L.E.
0000 3F3F 3F3F 3F00  ..?????.

background.js:6381 readPacket
background.js:6381 _readPacketSize
background.js:6381 _readPacketSize - 2
background.js:6381 readPacket: 35
background.js:6388 FF53 4D42 7522 0000 C088 01C8 0000 0000  .SMBu"..........
0000 0000 0000 0000 0000 0200 6400 0400  ............d...
0000 00 ...

**Comment by yoichiro** [comment]
@KevinTho Hmm... The log represented that the communication was successfully. Can you access to the target server from your pc (Windows or etc)? If yes, it would be great if you can capture packets and send it by the following steps:
https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-capture-packets-with-Wireshark

**Comment by KevinTho** [comment]
Have sent a trace file via email

**Comment by yoichiro** [comment]
@KevinTho Thanks! I got the log, and I intend to check it. Give me a few days.

**Comment by yoichiro** [comment]
Now checking... Well, I found the following differences:
- TreeConnectAndxRequest
  - Header/Flags: Success=0xc807 Failure=0xc803 ("Security Signatures: Security signatures are supported" not specified.)
  - Parameter/Flags: Success=0x0008 Failure=0x0000 ("Extended Response: Extended Response" not specified.)
  - Data/Path: Success=\STORAGE-105\TOURO_MOBILE Failure=\192.168.0.9\TOURO_MOBILE

**Comment by yoichiro** [comment]
@KevinTho I also found a wroung value of the User ID. For instance, like the following:
1. The FSP app sends a 1st SessionSetupAndxRequest which has 0 as the User ID.
2. The server returns a 1st SessionSetupAndxResoinse which has 0x64 as the User ID.
3. The FSP app sends a 2nd SessionSetupAndxRequest which has 0x64 as the User ID.
4. The server returns a 2nd SessionSetupAndxResponse which has 0x65 as the User ID.
5. The FSP app sends a 1st TreeConnectAndxRequest which has 0x64 as the User ID.

That is... The User ID value was changed while setting up the session. However, my FSP app is using the old User ID value for the next request. I think that I could recognize a situation which the nt_status_access_denied error occurred. In this case, the TreeConnectAndxRequest should be rejected anytime, because the specified User ID was already invalid...

OK, I guess that I can fix this issue, and will start coding to modify the logic for the User ID.

**Comment by yoichiro** [comment]
@KevinTho I have just released a new version 2.3.1. This version includes the modification about User ID problem. Could you test the version on your environment?

**Comment by didtoknan** [comment]
I'm not Kevin, but now it works for me ! I can access my readyshare server. Thanks a lot !

**Comment by KevinTho** [comment]
Hi Yoichiro, that has fixed it for me ! Many thanks.

**Comment by yoichiro** [comment]
@KevinTho @didtoknan OK, thank you for feedbacks from you! I close this issue.
