### ISSUE TITLE
 3221225506 NT_STATUS_ACCESS_DENIED error 

### ISSUE THREAD

**Issue by magic12** [yoichiro/chromeos-filesystem-cifs#115]
I am trying to connect to the hard drive connected to my Dlink DIR860L router.
I am entering the IP address of my router,server port as default 445, username and password but always getting this error. Please advise.

**Comment by yoichiro** [comment]
@magic12 Could you post the debug log by the following steps?
https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by jjquin** [comment]
I have this same issue connecting to the drive on my Netgear R7000.  Same exact error.  Here is my debug log.  
![screenshot 2015-09-27 at 7 34 25 pm](https://cloud.githubusercontent.com/assets/14864690/10125808/ac51d018-654f-11e5-83f5-fda900acb3bf.png)

**Comment by magic12** [comment]
Sorry for the delay in replying. Please see the log below.


background.js:6395 Domain name not specified. '?' will be applied.
background.js:6388 connect
background.js:6388 Header
background.js:6388 NegotiateProtocolRequest
background.js:6388 Packet
background.js:6395 Negotiated with SMB1/CIFS
background.js:6395 CAP_EXTENDED_SECURITY: true
background.js:6395 CAP_COMPRESSED_DATA: false
background.js:6395 CAP_BULK_TRANSFER: false
background.js:6395 CAP_UNIX: true
background.js:6395 CAP_LARGE_WRITEX: true
background.js:6395 CAP_LARGE_READX: true
background.js:6395 CAP_INFOLEVEL_PASSTHROUGH: true
background.js:6395 CAP_DFS: true
background.js:6395 CAP_NT_FIND: true
background.js:6395 CAP_LOCK_AND_READ: true
background.js:6395 CAP_LEVEL_II_OPLOCKS: true
background.js:6395 CAP_STATUS32: true
background.js:6395 CAP_RPC_REMOTE_APIS: true
background.js:6395 CAP_NT_SMBS: true
background.js:6395 CAP_LARGE_FILES: true
background.js:6395 CAP_UNICODE: true
background.js:6395 CAP_MPX_MODE: false
background.js:6395 CAP_RAW_MODE: true
background.js:6395 NEGOTIATE_SECURITY_SIGNATURES_REQUIRED: 0
background.js:6395 NEGOTIATE_SECURITY_SIGNATURES_ENABLED: 0
background.js:6395 NEGOTIATE_SECURITY_CHALLENGE_RESPONSE: 1
background.js:6395 NEGOTIATE_SECURITY_USER_LEVEL: 1
background.js:6388 Header
background.js:6388 NegotiateProtocolResponse
background.js:6388 Header
background.js:6388 SessionSetupAndxRequest
background.js:6388 Packet
background.js:6388 Header
background.js:6395 NTLMSSP_NEGOTIATE_UNICODE: true
background.js:6395 NTLMSSP_NEGOTIATE_OEM: false
background.js:6395 NTLMSSP_REQUEST_TARGET: true
background.js:6395 NTLMSSP_NEGOTIATE_SIGN: false
background.js:6395 NTLMSSP_NEGOTIATE_SEAL: false
background.js:6395 NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
background.js:6395 NTLMSSP_NEGOTIATE_LM_KEY: false
background.js:6395 NTLMSSP_NEGOTIATE_NETWARE: false
background.js:6395 NTLMSSP_NEGOTIATE_NTLM: true
background.js:6395 NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
background.js:6395 NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
background.js:6395 NTLMSSP_NEGOTIATE_LOCAL_CALL: false
background.js:6395 NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
background.js:6395 NTLMSSP_TARGET_TYPE_DOMAIN: false
background.js:6395 NTLMSSP_TARGET_TYPE_SERVER: true
background.js:6395 NTLMSSP_TARGET_TYPE_SHARE: false
background.js:6395 NTLMSSP_NEGOTIATE_NTLM2: true
background.js:6395 NTLMSSP_REQUEST_INIT_RESPONSE: false
background.js:6395 NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
background.js:6395 NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
background.js:6395 NTLMSSP_NEGOTIATE_TARGET_INFO: true
background.js:6395 NTLMSSP_NEGOTIATE_128: true
background.js:6395 NTLMSSP_NEGOTIATE_KEY_EXCH: false
background.js:6395 NTLMSSP_NEGOTIATE_56: false
background.js:6388 Header
background.js:6388 SessionSetupAndxRequest
background.js:6388 Packet
background.js:6388 Header
background.js:6388 TreeConnectAndxRequest
background.js:6388 Packet
background.js:15146 3221225506: NT_STATUS_ACCESS_DENIED

**Comment by yoichiro** [comment]
@magic12 @jjquin Hmm... I could not find any reason why this error occurred. So, I would like to know the packets which you access to the server from your pc successfully. Could you capture the packets by the following steps?
https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-capture-packets-with-Wireshark

**Comment by yoichiro** [comment]
@magic12 @jjquin Sorry, the packets collecting is unnecessary. I found the reason of the NT_STATUS_ACCESS_DENIED. Please see the comment: https://github.com/yoichiro/chromeos-filesystem-cifs/issues/109#issuecomment-147560322

**Comment by yoichiro** [comment]
@magic12 @jjquin I have just released a new version 2.3.1. This version includes the modification about User ID problem. Could you test the version on your environment?

**Comment by yoichiro** [comment]
@magic12 @jjquin Ping.

**Comment by jjquin** [comment]
Sorry it took so long for me to get back to you. It's my daughter's
Chromebook and I finally got my hands on it. I tested it and it worked
perfectly. Thank you for resolving this issue so quickly!

Thanks

J J Quin

P S Not really an issue just a minor annoyance. In the Chromebook file app,
I'm connected to 2 shares on the same drive plugged into my router. In the
folder list on the left both connections just show as the ip address of the
router. Figured it would be easier for people with several connections if
they displayed by share name or if you could give them a custom name. Again
this is just a cosmetic annoyance.

**Comment by yoichiro** [comment]
@jjquin Thank you for the feedback. Yes, I intend to think about the idea. I close this issue.
