### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by ericlmccormick** [yoichiro/chromeos-filesystem-cifs#119]
I have used this plug in on and off with 2 different Chrome OS devices. However I rarely use it because it is very slow. I thought it might have been something dealing with my network NAS but using samba with my Android phone and my Windows7 PC, everything runs fast. Not sure what the issue might be.

**Comment by yoichiro** [comment]
@ericlmccormick I want to know how long was each operation.

**Comment by ericlmccormick** [comment]
Just to pull up the contents of a folder can take up to 30sec and I get a
message saying it is taking longer than normal and ask if I want to abort.
Eric

**Comment by yoichiro** [comment]
@ericlmccormick Could you post the debug log here by the following steps?
https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by ericlmccormick** [comment]
It does seem to be working a little better today. Attached is a copy of the
log. It looks like the first time it sees a folder, it downloads a lots and
then future request of that folder are much faster. When using my phone, it
is just grabbing a list of the files and not trying to get images for
thumbnails and such. With a Windows PC, I think the order of operations is
a little different and will stop scanning a folder if I choose something
else.  With your extension, it looks like it needs to finish scanning the
folder before it moves on.
Is there anyway to force a scan the whole structure in the background so
that is can build whatever it needs before I attempt to access it for the
first time?

**Comment by yoichiro** [comment]
@ericlmccormick Thank you for the feedback. I intend to impletemt a new feature to abort operations.
