### ISSUE TITLE
Readyshare problems

### ISSUE THREAD

**Issue by WillemChromebook** [yoichiro/chromeos-filesystem-cifs#121]
Hi,

I have problems hooking up netgear's readyshare network drive. I have successfully hooked it to my mac and android tablet. Since it is on my regular router in the most basic way I do not need to give passwords, etc.  Below are some screen shots. Thanks!

**Comment by WillemChromebook** [comment]
Here are the screen shots

![screenshot 2015-09-18 at 17 17 21](https://cloud.githubusercontent.com/assets/13853656/9971489/1cf99ef4-5e2a-11e5-870f-1077e0651bee.png)

message name not resolved

![screenshot 2015-09-18 at 17 25 14](https://cloud.githubusercontent.com/assets/13853656/9971513/51eb5cb0-5e2a-11e5-8da1-067c4b5af005.png)

message name not resolved

![screenshot 2015-09-18 at 17 27 36](https://cloud.githubusercontent.com/assets/13853656/9971544/a3163f42-5e2a-11e5-8423-ef79af2dd4b6.png)

attempting to mount item, timeout

![screenshot 2015-09-18 at 17 29 44](https://cloud.githubusercontent.com/assets/13853656/9971582/f97eeff0-5e2a-11e5-9617-75d28888bbe4.png)

attempting to mount item, timeout

**Comment by yoichiro** [comment]
@WillemChromebook You must fill in the "Server name" or "IP Address" only to the "Server Host Name/IP Address" field. The "smb://" protocol identifier is unnecessary.

**Comment by WillemChromebook** [comment]
Thank you for your quick reaction! I tried the examples shown in the
screenshots (I got new router and had to change IP address) and I did not
succeed to mount readyshare.
When using the IP address (without smb:\) the first two examples geve the
error message NT status access denied. When using readyshare (without
smb:\) the last two examples gave the error message name not resolved.

I hope this helps to diagnose the problem

Willem

On Sat, Sep 19, 2015 at 9:30 AM, Yoichiro Tanaka notifications@github.com
wrote:

> @WillemChromebook https://github.com/WillemChromebook You must fill in
> the "Server name" or "IP Address" only to the "Server Host Name/IP Address"
> field. The "smb://" protocol identifier is unnecessary.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yoichiro/chromeos-filesystem-cifs/issues/121#issuecomment-141668127
> .

## 

Willem Windig
