### ISSUE TITLE
NT_STATUS_ACCESS_DENIED on samba 3.0.37

### ISSUE THREAD

**Issue by unixbulletin** [yoichiro/chromeos-filesystem-cifs#126]
Hi,

this app is compatible with samba 3.0.37?. When I try to connect I get the message "NT_STATUS_ACCESS_DENIED"

Thanks

**Comment by yoichiro** [comment]
@unixbulletin Could you post the debug log by the following steps?
https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by yoichiro** [comment]
@unixbulletin Sorry, the log submission is unnecessary. I found the reason why the NT_STATUS_ACCESS_DENIED" error occurred. Please see: https://github.com/yoichiro/chromeos-filesystem-cifs/issues/109#issuecomment-147560322

**Comment by yoichiro** [comment]
@unixbulletin I have just released a new version 2.3.1. This version includes the modification about User ID problem. Could you test the version on your environment?

**Comment by yoichiro** [comment]
@unixbulletin Ping.

**Comment by yoichiro** [comment]
@unixbulletin I close this issue, because you didn't give me more information. Thank you for your feedback.
