### ISSUE TITLE
Won't mount volume from zyxel NSA325 NAS

### ISSUE THREAD

**Issue by wolfchimneyrock** [yoichiro/chromeos-filesystem-cifs#13]
ChromeOS version: 
Version 43.0.2357.81 beta (64-bit)
Platform 6946.55.0 (Official Build) beta-channel falco
Firmware Google_Falco.4389.92.0

NAS linux version:
Linux NSA325 2.6.31.8 #2 Mon Aug 11 16:32:01 CST 2014 armv5tel GNU/Linux
NAS smb.conf:
[global]
        workgroup = WORKGROUP
        server string = NSA325
        netbios name = NSA325
        dos charset = UTF8
        display charset = UTF8
        unix charset = UTF8
        security = user
        encrypt passwords = yes
        smb passwd file = /etc/samba/smbpasswd
        guest account = pc-guest
        map to guest = Bad User
        write ok = yes
        force create mode = 777
        force directory mode = 777
        force security mode = 777
        force directory security mode = 777
        auth methods = guest sam_ignoredomain
        max log size = 50
        host msdfs = yes
        lanman auth = yes
        kernel oplocks = no
        socket options = IPTOS_LOWDELAY TCP_NODELAY SO_SNDBUF=131072 SO_RCVBUF=131072
        use mmap = yes
        max xmit = 131072
        min receivefile size = 128k
        unix extensions = no
        wide links = Yes
        oplocks = yes
        level2 oplocks = no
        max smbd processes = 128
        printing = cups
        printcap = /etc/printcap
 auth methods = guest sam_ignoredomain
        max log size = 50
        host msdfs = yes
        lanman auth = yes
        kernel oplocks = no
        socket options = IPTOS_LOWDELAY TCP_NODELAY SO_SNDBUF=131072 SO_RCVBUF=131072
        use mmap = yes
        max xmit = 131072
        min receivefile size = 128k
        unix extensions = no
        wide links = Yes
        oplocks = yes
        level2 oplocks = no
        max smbd processes = 128
        printing = cups
        printcap = /etc/printcap
        load printers = yes
        use sendfile = yes
        passdb backend = smbpasswd
        veto files = /.grive*/

**Share info removed***

**Comment by yoichiro** [comment]
@wolfchimneyrock Could you confirm the debug console output? You can check it out by the step below:
https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by yoichiro** [comment]
@wolfchimneyrock I close this issue, because you didn't provide enough information to solve this issue. Sorry, you can re-open this issue, if you get other information. And, try the latest version. Thank you for the reporting.

**Comment by wolfchimneyrock** [comment]
Sorry, for not replying.  The newer version works perfectly.

**Comment by yoichiro** [comment]
@wolfchimneyrock Oh, it's a good news to me. :)
