### ISSUE TITLE
Directory not visible (appears in logs though) for canon scanner

### ISSUE THREAD

**Issue by akanalytics** [yoichiro/chromeos-filesystem-cifs#130]
I have a canon printer/scanner which shares it memory card via samba/cifs (port 139)
All seems to work but the two directories IMAGE and DOCUMENT do not appear in the files browser on chromebook (parent directory does)

Snippet from consol log files

Packet {types_: Types, data_: ArrayBuffer, dataLength_: 102, packetHelper_: PacketHelper}
background.js:6381 writePacket
background.js:6388 FF53 4D42 3200 0000 0018 03C8 0000 0000  .SMB2...........
0000 0000 0000 0000 DC38 0100 6500 1C00  .........8..e...
0F24 0000 0000 0400 0400 0000 0000 0000  .$..............
0000 0024 0042 0000 0000 0001 0001 0025  ...$.B.........%
0000 1600 C800 0000 0401 0000 0000 5C00  ...............
4300 4100 4E00 4F00 4E00 5F00 5300 4300  C.A.N.O.N._.S.C.
5C00 2A00 0000  .*...

background.js:6381 readPacket
background.js:6381 _readPacketSize
background.js:6381 _readPacketSize - 2
background.js:6381 readPacket: 476
background.js:6388 FF53 4D42 3200 0000 0080 0080 0000 0000  .SMB2...........
0000 0000 0000 0000 DC38 0100 6500 1C00  .........8..e...
0A0A 0098 0100 000A 0038 0000 0098 0144  .........8.....D
0000 0000 00A5 0100 0000 0400 0100 0000  ................
0000 0000 6000 0000 0000 0000 00CF 7881  ....`.........x.
9CBC CC01 0098 E161 03BC CC01 00CF 7881  .......a......x.
9CBC CC01 0000 0000 0000 0000 0000 0000  ................
0000 0000 0000 0000 0000 0000 1000 0000  ................
0200 0000 0000 0000 0000 0000 4E00 5F00  ............N._.
5300 4300 0000 0098 E161 03BC CC01 00CF  S.C......a......
7881 2E00 6200 0000 0000 0000 00CF 7881  x...b.........x.
9CBC CC01 0098 E161 03BC CC01 00CF 7881  .......a......x.
9CBC CC01 0000 0000 0000 0000 0000 0000  ................
0000 0000 0000 0000 0000 0000 1000 0000  ................
0400 0000 0000 0000 0000 0000 0000 0000  ................
0000 0000 0000 0000 0000 0000 0000 0000  ................
0000 2E00 2E00 6E00 0000 0000 0000 00CF  ......n.........
7881 9CBC CC01 0098 E161 03BC CC01 00CF  x........a......
7881 9CBC CC01 0000 0000 0000 0000 0000  x...............
0000 0000 0000 0000 0000 0000 0000 1000  ................
0000 1000 0000 0000 0000 0000 0000 0000  ................
0000 1000 0000 0A00 0000 4900 4D00 4100  ..........I.M.A.
4700 4500 4400 4F00 4300 5500 4D00 4500  G.E.D.O.C.U.M.E.
4E00 5400 6800 0000 0000 0000 0013 C40E  N.T.h...........
E80C CE01 0098 AE4A 560C CE01 0013 C40E  .......JV.......
E80C CE01 0000 0000 0000 0000 0000 0000  ................
0000 0000 0000 0000 0000 0000 1000 0000  ................
0A00 0000 0000 0000 0000 0000 0000 0000  ................
0000 0000 0000 0000 0000 0000 0000 0000  ................
0000 4900 4D00 4100 4700 4500  ..I.M.A.G.E.

background.js:6388 Header {types_: Types, protocol_: "SMB", command_: 50, errorClass_: 0, errorCode_: 0…}
background.js:6388 FindFirst2Response {types_: Types, responseUtils_: ResponseUtils, searchId_: 0, searchCount_: 4, endOfSearch_: 1…}
background.js:6388 Header {types_: Types, protocol_: "SMB", command_: 52, errorClass_: 0, errorCode_: 0…}
background.js:6388 FindClose2Request {types_: Types, searchId_: 0}
background.js:6381 writePacket
background.js:6388 FF53 4D42 3400 0000 0018 03C8 0000 0000  .SMB4...........
0000 0000 0000 0000 DC38 0100 6500 1D00  .........8..e...
0100 0000 00 .....

background.js:6381 readPacket
background.js:6381 _readPacketSize
background.js:6381 _readPacketSize - 2
background.js:6381 readPacket: 35
background.js:6388 FF53 4D42 3400 0000 0080 0080 0000 0000  .SMB4...........
0000 0000 0000 0000 DC38 0100 6500 1D00  .........8..e...
0000 00 ...

background.js:6381 Object {metadataList: Array[0]}
background.js:6381 TaskQueue: consumeTask - queue: empty

initial connection:

Negotiated with SMB1/CIFS
background.js:6395 CAP_EXTENDED_SECURITY: false
background.js:6395 CAP_COMPRESSED_DATA: false
background.js:6395 CAP_BULK_TRANSFER: false
background.js:6395 CAP_UNIX: false
background.js:6395 CAP_LARGE_WRITEX: false
background.js:6395 CAP_LARGE_READX: false
background.js:6395 CAP_INFOLEVEL_PASSTHROUGH: false
background.js:6395 CAP_DFS: false
background.js:6395 CAP_NT_FIND: true
background.js:6395 CAP_LOCK_AND_READ: false
background.js:6395 CAP_LEVEL_II_OPLOCKS: false
background.js:6395 CAP_STATUS32: false
background.js:6395 CAP_RPC_REMOTE_APIS: false
background.js:6395 CAP_NT_SMBS: true
background.js:6395 CAP_LARGE_FILES: false
background.js:6395 CAP_UNICODE: true
background.js:6395 CAP_MPX_MODE: false
background.js:6395 CAP_RAW_MODE: false
background.js:6395 NEGOTIATE_SECURITY_SIGNATURES_REQUIRED: 0
background.js:6395 NEGOTIATE_SECURITY_SIGNATURES_ENABLED: 0
background.js:6395 NEGOTIATE_SECURITY_CHALLENGE_RESPONSE: 1
background.js:6395 NEGOTIATE_SECURITY_USER_LEVEL: 1
background.js:6388 Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}

**Comment by yoichiro** [comment]
@akanalytics It seems that the log above is not enough. Probably, I think that there are more log line count... Could you re-post your log (between 1st line and last line) here?

**Comment by yoichiro** [comment]
@akanalytics Ping.

**Comment by yoichiro** [comment]
@akanalytics I close this issue, because you didn't provide more information to fix this issue. Thank you for this report.
