### ISSUE TITLE
Readyshare issue

### ISSUE THREAD

**Issue by didtoknan** [yoichiro/chromeos-filesystem-cifs#131]
Hi,

It's at least the 3rd issue about that subject but the others are closed without a solution.
I tried the server name "readyshare" and also the IP server "192.168.1.1". 
Both are working fine on Windows and Android.

With the ip address, the error is 3221225506 NT_STATUS_ACCESS_DENIED.
With the server name, it's net:ERR_NAME_NOT_RESOLVED

Can you please help me ?
Do you need more information ?
How important is the server port number ? Could it be the problem ?

**Comment by didtoknan** [comment]
I can access to my desktop using this app, but I still can't access to the readyshare server.
I guess there is no solution.

**Comment by yoichiro** [comment]
@didtoknan Duplicated issue as #128.
