### ISSUE TITLE
Cannot connect to Windows 2008R2 with domain account

### ISSUE THREAD

**Issue by Sanmina** [yoichiro/chromeos-filesystem-cifs#132]
Hi
I can connect to the 2008R2 Server using a local account created on the server, but when i try to use a domain account i get NT status logon failure. I know that i have the NTLMV authentication right. Can you point me in the right direction to start looking ? 

Debug log:
Looked up with chrome.mdns:  Array[0]
background.js:6388 connect
background.js:6388 Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
background.js:6388 NegotiateProtocolRequest {types_: Types, dialects: Array[0], dialects_: Array[2]}
background.js:6388 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 58, packetHelper_: PacketHelper}
background.js:6395 Negotiated with SMB2
background.js:6388 Asn1Obj {tag_: 96, value_: null, children_: Array[2]}
background.js:6395 SPNEGO = true
background.js:6395 Supported mechType: 1.3.6.1.4.1.311.2.2.30
background.js:6395 Supported mechType: 1.2.840.6144018.1.2.2
background.js:6395 Supported mechType: 1.2.840.14532626.1.2.2
background.js:6395 Supported mechType: 1.2.840.14532626.1.2.2.3
background.js:6395 Supported mechType: 1.3.6.1.4.1.311.2.2.10
background.js:6388 Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 0, channelSequence_: 0…}
background.js:6388 NegotiateResponse {types_: Types, structureSize_: 65, securityMode_: 1, dialectRevision_: 514, serverGuid_: "����ԫwL�����w"…}
background.js:6388 Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}
background.js:6388 SessionSetupRequest {types_: Types, flags_: 0, securityMode_: 1, capabilities_: 1, channel_: 0…}
background.js:6388 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 163, packetHelper_: PacketHelper}
background.js:6388 Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 22…}
background.js:6388 Asn1Obj {tag_: 161, value_: null, children_: Array[1]}
background.js:6395 Response OID = 1.3.6.1.4.1.311.2.2.10
background.js:6395 NTLMSSP_NEGOTIATE_UNICODE: true
background.js:6395 NTLMSSP_NEGOTIATE_OEM: false
background.js:6395 NTLMSSP_REQUEST_TARGET: true
background.js:6395 NTLMSSP_NEGOTIATE_SIGN: false
background.js:6395 NTLMSSP_NEGOTIATE_SEAL: false
background.js:6395 NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
background.js:6395 NTLMSSP_NEGOTIATE_LM_KEY: false
background.js:6395 NTLMSSP_NEGOTIATE_NETWARE: false
background.js:6395 NTLMSSP_NEGOTIATE_NTLM: true
background.js:6395 NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
background.js:6395 NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
background.js:6395 NTLMSSP_NEGOTIATE_LOCAL_CALL: false
background.js:6395 NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
background.js:6395 NTLMSSP_TARGET_TYPE_DOMAIN: true
background.js:6395 NTLMSSP_TARGET_TYPE_SERVER: false
background.js:6395 NTLMSSP_TARGET_TYPE_SHARE: false
background.js:6395 NTLMSSP_NEGOTIATE_NTLM2: true
background.js:6395 NTLMSSP_REQUEST_INIT_RESPONSE: false
background.js:6395 NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
background.js:6395 NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
background.js:6395 NTLMSSP_NEGOTIATE_TARGET_INFO: true
background.js:6395 NTLMSSP_NEGOTIATE_128: true
background.js:6395 NTLMSSP_NEGOTIATE_KEY_EXCH: false
background.js:6395 NTLMSSP_NEGOTIATE_56: false
background.js:6388 Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}
background.js:6388 SessionSetupRequest {types_: Types, flags_: 0, securityMode_: 1, capabilities_: 1, channel_: 0…}
background.js:6388 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 458, packetHelper_: PacketHelper}

**Comment by Sanmina** [comment]
Do you have a Answer for the Problem??

**Comment by yoichiro** [comment]
@Sanmina Hey, I already read this issue, therefore, don't close and re-open for notifying!

**Comment by yoichiro** [comment]
@Sanmina Change the log level to Debug on the setting panel where clicking the gear icon on the login panel of this app, re-collect the console logs on the DevTools and post them here.

**Comment by yoichiro** [comment]
@Sanmina  I found a bug regarding authentication. It was described at the following post: https://plus.google.com/u/0/+YoichiroTanaka/posts/EEJyicfnSqK I have already released a new version 2.4.0 including code to fix the problem.

Could you check whether or not this new version works on your environment?

**Comment by yoichiro** [comment]
@Sanmina Ping.

**Comment by Sanmina** [comment]
Thxs i will check it and let you know

**Comment by yoichiro** [comment]
@Sanmina Ping.

**Comment by yoichiro** [comment]
I close this issue, because @Sanmina didn't provide more information to fix this issue. Thank you for the reporting.
