### ISSUE TITLE
Cannot connect to Windows 2008R2 with domain account

### ISSUE THREAD

**Issue by Sanmina** [yoichiro/chromeos-filesystem-cifs#133]
Hi
I can connect to the 2008R2 Server using a local account created on the server, but when i try to use a domain account i get NT status logon failure. I know that i have the NTLMV authentication right. Can you point me in the right direction to start looking ? 

connect
background.js:6388 Header
background.js:6388 NegotiateProtocolRequest
background.js:6388 Packet
background.js:6395 Negotiated with SMB2
background.js:6388 Asn1Obj
background.js:6395 SPNEGO = true
background.js:6395 Supported mechType: 1.3.6.1.4.1.311.2.2.30
background.js:6395 Supported mechType: 1.2.840.6144018.1.2.2
background.js:6395 Supported mechType: 1.2.840.14532626.1.2.2
background.js:6395 Supported mechType: 1.2.840.14532626.1.2.2.3
background.js:6395 Supported mechType: 1.3.6.1.4.1.311.2.2.10
background.js:6388 Header
background.js:6388 NegotiateResponse
background.js:6388 Header
background.js:6388 SessionSetupRequest
background.js:6388 Packet
background.js:6388 Header
background.js:6388 Asn1Obj
background.js:6395 Response OID = 1.3.6.1.4.1.311.2.2.10
background.js:6395 NTLMSSP_NEGOTIATE_UNICODE: true
background.js:6395 NTLMSSP_NEGOTIATE_OEM: false
background.js:6395 NTLMSSP_REQUEST_TARGET: true
background.js:6395 NTLMSSP_NEGOTIATE_SIGN: false
background.js:6395 NTLMSSP_NEGOTIATE_SEAL: false
background.js:6395 NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
background.js:6395 NTLMSSP_NEGOTIATE_LM_KEY: false
background.js:6395 NTLMSSP_NEGOTIATE_NETWARE: false
background.js:6395 NTLMSSP_NEGOTIATE_NTLM: true
background.js:6395 NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
background.js:6395 NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
background.js:6395 NTLMSSP_NEGOTIATE_LOCAL_CALL: false
background.js:6395 NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
background.js:6395 NTLMSSP_TARGET_TYPE_DOMAIN: true
background.js:6395 NTLMSSP_TARGET_TYPE_SERVER: false
background.js:6395 NTLMSSP_TARGET_TYPE_SHARE: false
background.js:6395 NTLMSSP_NEGOTIATE_NTLM2: true
background.js:6395 NTLMSSP_REQUEST_INIT_RESPONSE: false
background.js:6395 NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
background.js:6395 NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
background.js:6395 NTLMSSP_NEGOTIATE_TARGET_INFO: true
background.js:6395 NTLMSSP_NEGOTIATE_128: true
background.js:6395 NTLMSSP_NEGOTIATE_KEY_EXCH: false
background.js:6395 NTLMSSP_NEGOTIATE_56: false
background.js:6388 Header
background.js:6388 SessionSetupRequest
background.js:6388 Packet

**Comment by yoichiro** [comment]
@Sanmina Duplicated issue as #132
