### ISSUE TITLE
READYSHARE ON CHROMEBOOK WORKS

### ISSUE THREAD

**Issue by WillemChromebook** [yoichiro/chromeos-filesystem-cifs#137]
Thanks for taking care of this! You just have to type the ip address of router, without smb befor it!

**Comment by yoichiro** [comment]
@WillemChromebook Well, do you think that it is an issue? Sorry, I cannot understand the meaning you said.

**Comment by WillemChromebook** [comment]
It works fine! I just wanted to thank you for your work. In an earlier note
to me you said that smb:// should not be in the first field, so I just
repeat that.
Thanks again!

Willem

On Wed, Oct 14, 2015 at 6:01 PM, Yoichiro Tanaka notifications@github.com
wrote:

> @WillemChromebook https://github.com/WillemChromebook Well, do you
> think that it is an issue? Sorry, I cannot understand the meaning you said.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yoichiro/chromeos-filesystem-cifs/issues/137#issuecomment-148215791
> .

## 

Willem Windig

**Comment by yoichiro** [comment]
@WillemChromebook Haha, my pleasure. I must say thank you because your contribution was valuable. You can close this issue, if possible.
