### ISSUE TITLE
Can't mount volume from an Asus Router

### ISSUE THREAD

**Issue by mattsjo** [yoichiro/chromeos-filesystem-cifs#14]
Hi,
Thank you for all your file system extensions! Eventually I usually get them to work but I can't get around this one...

I'm trying to mount a share from my Router (Asus RT-AC66U running ASUSWRT-Merlin 378.52_2) and it fails... 

This is the output from the console on my Chromebook (stable-channel peach_pi):

Object {type: "getSharedResources", serverName: "192.168.0.1", serverPort: "445", username: "Mattias", password: "secret"}

This is the system log entry on the Router:

Jun  2 19:00:42 smbd[32594]: [2015/06/02 19:00:42.480506,  0] smbd/sesssetup.c:1355(reply_sesssetup_and_X)
Jun  2 19:00:42 smbd[32594]:   reply_sesssetup_and_X:  Rejecting attempt at SPNEGO session setup when it was not negotiated.

I have tried both with and without requiring login in the router.

I googled the error and found this, I don't know if it helps...
http://www.snbforums.com/threads/weird-messages-on-rt-ac66u.23892/

**Comment by yoichiro** [comment]
@mattsjo Did you try to mount your ROUTER???

**Comment by mattsjo** [comment]
Yes.
It's possible to connect USB drives to the router and a samba server makes
it act just like a NAS.
As indicated by the router log entry, the samba server gets the request but
authentication can't be done.

/Mattias
Den 4 jun 2015 2:27 fm skrev "Yoichiro Tanaka" notifications@github.com:

**Comment by yoichiro** [comment]
@mattsjo I have released a new version 1.1.4. In the version, the app supports LMv1 and NTLMv1 authentication. Probably, I guess that your router does not support LMv2 and NTLMv2. If my idea is correct, you should success to mount your router. Could you confirm whether you can mount your router with 1.1.4?

**Comment by mattsjo** [comment]
Now on version 1.1.8 and the error message is "Extended security not supported". Any chance of supporting normal security? :-)

**Comment by mattsjo** [comment]
Sorry, pressed the wrong button...

**Comment by yoichiro** [comment]
@mattsjo The current version doesn't support the unextended security server. Please see #48. I close this issue. Thank you for the reporting.

**Comment by mattsjo** [comment]
Just to let everyone know... It now works! (tested on release 1.4.0)
You have to have guest mode enabled (no password required) otherwise this error is displayed:
2147483653 UNKNOWN

There is no error in the router log.

Thanks!
