### ISSUE TITLE
new user - how to access files

### ISSUE THREAD

**Issue by d3xt3r67** [yoichiro/chromeos-filesystem-cifs#142]
Hi guys,
I have a chromebox and found your app to have access to my shared files. i managed to create and mount my servers ( 1 windows 10 and 1 linux (geexbox)). the mounting is successful but how do I access my shared files ???? 

maybe I missed something ?

**Comment by yoichiro** [comment]
@d3xt3r67 You can access to your directories/files on Files app after mounting your shared resource.

![screenshot 2015-10-26 at 8 56 22 pm](https://cloud.githubusercontent.com/assets/261787/10728319/20f262ee-7c24-11e5-9a68-737e3377d015.png)

**Comment by d3xt3r67** [comment]
Hey thanks a lot for the fast reply
