### ISSUE TITLE
Failure during use: Some operations are taking longer than expected

### ISSUE THREAD

**Issue by Subrosian** [yoichiro/chromeos-filesystem-cifs#144]
On my Dell Chromebook 13 running ChromeOS Version 46.0.2490.71 (64-bit), using "File System for Windows 2.6.0", I can browse my remote fileshare, but when trying to copy a file from the location to my local computer, I get the error below. I have also gotten this error when browsing the directory tree for a few minutes, though it works ok for the first few minutes. The share is hosted on a Server 2012 R2 installation with all of the enhanced CIFS protections disabled to be used properly in certain Linux environments (like Openelec). Also, I have ruled out wireless issues by using a USB Gigabit Ethernet adapter that is compatible with ChromeOS.

I created a different bug for this as the logs in Issue #139 look different than mine. If it ends up being the same issue, please merge/close this one. 

![screenshot 2015-10-30 at 11 26 16 pm](https://cloud.githubusercontent.com/assets/15502619/10861668/33a25e2e-7f5f-11e5-83b9-7811909a93c5.png)

After clicking abort, i get the following. I don't know if it is useful at all:
![screenshot 2015-10-30 at 11 26 53 pm](https://cloud.githubusercontent.com/assets/15502619/10861669/33a4fef4-7f5f-11e5-8b93-9efa17ccb256.png)

**Comment by yoichiro** [comment]
It seems that this issue is same as #139. As the difference, this issue can be represented in the case of connecting with SMB2.

**Comment by yoichiro** [comment]
Fixed this issue on #147

**Comment by yoichiro** [comment]
@Subrosians I have released a new version 2.6.1 including code to fix this issue. Could you confirm whether or not this issue is reproduced?

**Comment by Subrosian** [comment]
First testing looks good as I have been unable to replicate the issue. I will continue testing and reopen if I can replicate.

**Comment by yoichiro** [comment]
@Subrosians Thank you for the confirmation.

**Comment by pyperdown** [comment]
I'm getting a connection but complains about "an operation is taking longer than expected"

Running against samba3 PDC/NT4 domain
