### ISSUE TITLE
App does nothing

### ISSUE THREAD

**Issue by selgar** [yoichiro/chromeos-filesystem-cifs#151]
I'm trying the app on a number of laptops and on each one, once installed I click on the app and all it seems to do is close the current tab in Chrome. I installed the app on a Chromebook (laptop running Neverware) and it app seems to work.

I tried the app on both Mac & PC. OSX Chrome version is 46.0.2490.80 (64-bit), Windows is 46.0.2490.86 m (64-bit).

**Comment by yoichiro** [comment]
This software can be worked on ChromeOS only.
