### ISSUE TITLE
Open Doc file doesnt open Google Docs

### ISSUE THREAD

**Issue by selgar** [yoichiro/chromeos-filesystem-cifs#152]
I guess this is perhaps a feature request rather than a bug but I have the app working on a Chromebook.

I can browse my server but when I click on a Microsoft Word (doc) file I would have hoped that it would open Google Docs whereas it just says that file is not supported.

I would also hope that the same would happen with Excel and Powerpoint files

**Comment by yoichiro** [comment]
@selgar I think that your request cannot be covered by my app. Currently, to determine an app to open the selected file is depended on the ChromeOS.
