### ISSUE TITLE
Failed to download to a NAS server

### ISSUE THREAD

**Issue by rdeg** [yoichiro/chromeos-filesystem-cifs#154]
Under Chrome, failed to directly download a file from the Internet to a folder of a NAS server.
I can download to the Download folder of my Chromebook and then copy the downloaded file to the NAS.
Error message as visible in the Download status bar of Chrome show something like "Failure - Downloading error" (in French : "Echec - Erreur lors du téléchargement").

**Comment by yoichiro** [comment]
Same as #60
