### ISSUE TITLE
Persistent Shares

### ISSUE THREAD

**Issue by jcrick69** [yoichiro/chromeos-filesystem-cifs#157]
Can the system persist a share/mount between sessions and different computers? 

Actually, I want the the share to be available after I switch from one Chromebook to another, assuming the Chromebook has access to the network of course.

Thanks, Jerry

**Comment by yoichiro** [comment]
@jcrick69 I think that a shareing of configurations can be implemented, but a sharing of such mounting state (ex. if you mount some server on your Chromebook A, the server is mounted automatically on your Chromebook B) cannot be implemented (at least, I don't want such feature).

For example, currently, the chrome.storage.local has been using: https://github.com/yoichiro/chromeos-filesystem-cifs/blob/master/app/scripts/window.js#L261 When I change it to the chrome.storage.sync, the configurations will be shared with your Google account. Is this the feature you're expecting?

**Comment by jcrick69** [comment]
OK, thanks. Actually, the mount is also lost when you logoff.

Jerry
