### ISSUE TITLE
Mounting share on Windows 2012 - Successful but only top folders (NT_STATUS_PATH_NOT_COVERED)

### ISSUE THREAD

**Issue by rcoleman91** [yoichiro/chromeos-filesystem-cifs#166]
Hi,
Attempting to mount SMB share hosted on Windows Server 2012 using domain credentials.

Share is mounted successfully but only the root directory folders are visible.
When opening any folder, nothing is visible.
NTFS permissions are confirmed not to be the cause as have tested with domain account with full permissions to everything with same results.
Log is attached.

**Comment by rcoleman91** [comment]
Have had to change extension to .txt to upload.

[mfhnnfciefdpolbelmfkpmhhmlkehbdf-1449463488022.txt](https://github.com/yoichiro/chromeos-filesystem-cifs/files/53470/mfhnnfciefdpolbelmfkpmhhmlkehbdf-1449463488022.txt)

**Comment by yoichiro** [comment]
@rcoleman91 Hmm... The error NT_STATUS_PATH_NOT_COVERED was occurred. I don't know the meaning of the error code... I intend to investigate the situation.

**Comment by yoichiro** [comment]
@rcoleman91 Are there some DFS links in the root folder?

**Comment by rcoleman91** [comment]
@yoichiro I have recently learned that there are DFS links..Is this a problem?

**Comment by yoichiro** [comment]
@rcoleman91 Probably, yes. As my understanding, if the error code NT_STATUS_PATH_NOT_COVERED returned, a SMB client needs to get the real location path and needs to re-mount the real server to access to the real folder. However, the latest version of this app doesn't have the ability. That is, actually, this app should redirect you to the real server when you specify the DFS shortcut, but this app cannot do its behavior.

I intend to register a new feature request to support the DFS as a new issue here. Therefore, I want to close this issue as wontfix, is this ok?

**Comment by rcoleman91** [comment]
@yoichiro 
Hi Yoichiro, fine to close based on the above info.
