### ISSUE TITLE
Can't connect, can't find "log" files

### ISSUE THREAD

**Issue by BAZZAB** [yoichiro/chromeos-filesystem-cifs#169]
I am using your Dropbox and it works great, but I've spent several hours trying to connect to a NAS drive on a DD-WRT router.  All I get is net:ERR NAME NOT RESOLVED.  I can connect to this NAS with Windows and Linux, but not with my Chromebook. 

Is there some way to make trace-log files visible so I can troubleshoot why I cannot get the network name to resolve? (will the log tell me anything more?)
I assume Server Host name / IP address must look like:  dd-wrt-ac1450 / 192.168.1.1 where dd-wrt is the device (and netbios) name, ac1450 is the server string, and this device is at the ip address shown.  Is that the correct format for the first line of the parameter?
Thank you for any suggestion you may have.  This is a very useful app and I'd like to get it working.

**Comment by yoichiro** [comment]
@BAZZAB My app doesn't support NetBIOS protocol. Therefore, you need to specify the server name which can be resolved by DNS server. Or, you can fill in the IP Address instead of the host name.

**Comment by BAZZAB** [comment]
Thank you Tanaka-san!  I was able to connect with only the IP address and logon information. Your app recognized the share names and I was able to select, and it mounted!

**Comment by yoichiro** [comment]
@BAZZAB OK, good. I close this issue. Thank you.
