### ISSUE TITLE
Add share scanning support.

### ISSUE THREAD

**Issue by ghost** [yoichiro/chromeos-filesystem-cifs#17]
It would be nice to be able to have a list of available shares listed from a network scan.

**Comment by yoichiro** [comment]
@brycethorup Probably, I can use a new API "chrome.mdns" to scan servers which can talk SMB protocol from the network. I try to implement this feature. Please give me a few weeks...

**Comment by KevinBLT** [comment]
Yes, I and I think many others (especially users who don't understand anything about IP's etc) 
would really appreciate this!
A big thank you for your great work! :-)

**Comment by yoichiro** [comment]
I have just released a new version 1.4.0 including a new feature to search SMB servers with mDNS. I close this issue.
