### ISSUE TITLE
Cannot create new folder

### ISSUE THREAD

**Issue by fn0v0tny** [yoichiro/chromeos-filesystem-cifs#173]
![screenshot 2016-01-02 at 20 47 36](https://cloud.githubusercontent.com/assets/8459180/12075902/16ec3556-b192-11e5-9847-810b70efb873.png)
There is written, that Creating folder “New Folder“ failed.  File or directory can not be used.
I can not create new folder on network drive.

**Comment by yoichiro** [comment]
Duplicated issue #172 . Close this.
