### ISSUE TITLE
Cannot Mount Drive

### ISSUE THREAD

**Issue by erikolsonAFN** [yoichiro/chromeos-filesystem-cifs#175]
I tried to mount a drive but am getting an error NT_Status_Logon_Failure.  If I keep trying to mount it, it will lock my AD account out so it appears to not be a syntax error but sending the wrong password.  I checked in the logs and it is showing the correct password.  I included the log but removed sensitive info such as username and password. Thank you.

NTLMSSP_NEGOTIATE_128: true
background.js:6531 NTLMSSP_NEGOTIATE_KEY_EXCH: false
background.js:6531 NTLMSSP_NEGOTIATE_56: false
background.js:6531 Use LMv2 and NTLMv2 because LMCompatibilityLevel=5
background.js:6524 Header
background.js:6524 SessionSetupRequest
background.js:6524 Packet
background.js:6517 Object {serverName: "{servername}", serverPort: "445", username: "{username}", password: "{password}", domainName: "{domain}"…}
background.js:6517 Client#login
background.js:6524 connect
background.js:6524 Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
background.js:6524 NegotiateProtocolRequest {types_: Types, dialects: Array[0], dialects_: Array[3]}
background.js:6524 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 69, packetHelper_: PacketHelper}
background.js:6517 writePacket
background.js:6524 FF53 4D42 7200 0000 0018 43C8 0000 0000  .SMBr.....C.....
0000 0000 0000 0000 0000 0300 0000 0000  ................
0022 0002 4E54 204C 4D20 302E 3132 0002  ."..NT LM 0.12..
534D 4220 322E 3030 3200 0253 4D42 2032  SMB 2.002..SMB 2
2E3F 3F3F 00 .???.

background.js:6517 readPacket
background.js:6517 _readPacketSize
background.js:6517 _readPacketSize - 2
background.js:6517 readPacket: 248
background.js:6524 FE53 4D42 4000 0000 0000 0000 0000 0100  .SMB@...........
0100 0000 0000 0000 0000 0000 0000 0000  ................
0000 0000 0000 0000 0000 0000 0000 0000  ................
0000 0000 0000 0000 0000 0000 0000 0000  ................
4100 0100 FF02 0000 19A7 3ED4 5548 B146  A.........>.UH.F
A8C4 A907 81D1 CCEF 0700 0000 0000 1000  ................
0000 1000 0000 1000 D69B 12B6 464E D101  ............FN..
4080 87BD 6138 D101 8000 7800 4C4D 5353  @...a8....x.LMSS
6076 0606 2B06 0105 0502 A06C 306A A03C  `v..+......l0j.<
303A 060A 2B06 0104 0182 3702 021E 0609  0:..+.....7.....
2A86 4882 F712 0102 0206 092A 8648 86F7  _.H........_.H..
1201 0202 060A 2A86 4886 F712 0102 0203  ......_.H.......
060A 2B06 0104 0182 3702 020A A32A 3028  ..+.....7...._0(
A026 1B24 6E6F 745F 6465 6669 6E65 645F  .&.$not_defined_
696E 5F52 4643 3431 3738 4070 6C65 6173  in_RFC4178@pleas
655F 6967 6E6F 7265  e_ignore

background.js:6531 Negotiated with SMB2
background.js:6524 Asn1Obj {tag_: 96, value_: null, children_: Array[2]}
background.js:6531 SPNEGO = true
background.js:6531 Supported mechType: 1.3.6.1.4.1.311.2.2.30
background.js:6531 Supported mechType: 1.2.840.6144018.1.2.2
background.js:6531 Supported mechType: 1.2.840.14532626.1.2.2
background.js:6531 Supported mechType: 1.2.840.14532626.1.2.2.3
background.js:6531 Supported mechType: 1.3.6.1.4.1.311.2.2.10
background.js:14754 Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 0, channelSequence_: 0…}
background.js:6524 Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 0, channelSequence_: 0…}
background.js:6524 NegotiateRequest {types_: Types, clientGuid_: Uint8Array[16]}
background.js:6524 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 104, packetHelper_: PacketHelper}
background.js:6517 writePacket
background.js:6524 FE53 4D42 4000 0000 0000 0000 0000 0000  .SMB@...........
0000 0000 0000 0000 0100 0000 0000 0000  ................
BECB 0000 0000 0000 0000 0000 0000 0000  ................
0000 0000 0000 0000 0000 0000 0000 0000  ................
2400 0200 0100 0000 0000 0000 F005 EE5D  $..............]
E671 ABEE CF6E 9B78 1653 A2D8 0000 0000  .q...n.x.S......
0000 0000 0202 1002  ........

background.js:6517 readPacket
background.js:6517 _readPacketSize
background.js:6517 _readPacketSize - 2
background.js:6517 readPacket: 248
background.js:6524 FE53 4D42 4000 0000 0000 0000 0000 0100  .SMB@...........
0100 0000 0000 0000 0100 0000 0000 0000  ................
BECB 0000 0000 0000 0000 0000 0000 0000  ................
0000 0000 0000 0000 0000 0000 0000 0000  ................
4100 0100 1002 0000 19A7 3ED4 5548 B146  A.........>.UH.F
A8C4 A907 81D1 CCEF 0700 0000 0000 1000  ................
0000 1000 0000 1000 F9BF 19B6 464E D101  ............FN..
4080 87BD 6138 D101 8000 7800 4C4D 5353  @...a8....x.LMSS
6076 0606 2B06 0105 0502 A06C 306A A03C  `v..+......l0j.<
303A 060A 2B06 0104 0182 3702 021E 0609  0:..+.....7.....
2A86 4882 F712 0102 0206 092A 8648 86F7  _.H........_.H..
1201 0202 060A 2A86 4886 F712 0102 0203  ......_.H.......
060A 2B06 0104 0182 3702 020A A32A 3028  ..+.....7...._0(
A026 1B24 6E6F 745F 6465 6669 6E65 645F  .&.$not_defined_
696E 5F52 4643 3431 3738 4070 6C65 6173  in_RFC4178@pleas
655F 6967 6E6F 7265  e_ignore

background.js:6524 Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 0, channelSequence_: 0…}
background.js:6524 Asn1Obj {tag_: 96, value_: null, children_: Array[2]}
background.js:6531 SPNEGO = true
background.js:6531 Supported mechType: 1.3.6.1.4.1.311.2.2.30
background.js:6531 Supported mechType: 1.2.840.6144018.1.2.2
background.js:6531 Supported mechType: 1.2.840.14532626.1.2.2
background.js:6531 Supported mechType: 1.2.840.14532626.1.2.2.3
background.js:6531 Supported mechType: 1.3.6.1.4.1.311.2.2.10
background.js:6524 Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 0, channelSequence_: 0…}
background.js:6524 NegotiateResponse {types_: Types, structureSize_: 65, securityMode_: 1, dialectRevision_: 528, serverGuid_: "�>�UH�F�ĩ����"…}
background.js:6524 Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}
background.js:6524 SessionSetupRequest {types_: Types, flags_: 0, securityMode_: 1, capabilities_: 1, channel_: 0…}
background.js:6524 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 163, packetHelper_: PacketHelper}
background.js:6517 writePacket
background.js:6524 FE53 4D42 4000 0100 0000 0000 0100 0100  .SMB@...........
0000 0000 0000 0000 0200 0000 0000 0000  ................
BECB 0000 0000 0000 0000 0000 0000 0000  ................
0000 0000 0000 0000 0000 0000 0000 0000  ................
1900 0001 0100 0000 0000 0000 5800 4B00  ............X.K.
0000 0000 0000 0000 6049 0606 2B06 0105  ........`I..+...
0502 A03F 303D A00E 300C 060A 2B06 0104  ...?0=..0...+...
0182 3702 020A A22B 0429 4E54 4C4D 5353  ..7....+.)NTLMSS
5000 0100 0000 15B2 0820 0100 0100 2000  P........ .... .
0000 0800 0800 2100 0000 3F46 5350 5F43  ......!...?FSP_C
4946 53 IFS

background.js:6517 readPacket
background.js:6517 _readPacketSize
background.js:6517 _readPacketSize - 2
background.js:6517 readPacket: 469
background.js:6524 FE53 4D42 4000 0100 1600 00C0 0100 0100  .SMB@...........
0100 0000 0000 0000 0200 0000 0000 0000  ................
BECB 0000 0000 0000 6100 003C 0004 0000  ........a..<....
0000 0000 0000 0000 0000 0000 0000 0000  ................
0900 0000 4800 8D01 A182 0189 3082 0185  ....H.......0...
A003 0A01 01A1 0C06 0A2B 0601 0401 8237  .........+.....7
0202 0AA2 8201 6E04 8201 6A4E 544C 4D53  ......n...jNTLMS
5350 0002 0000 0012 0012 0038 0000 0015  SP.........8....
8289 2272 2896 D9A4 A234 8800 0000 0000  .."r(....4......
0000 0020 0120 014A 0000 0006 01B1 1D00  ... . .J........
0000 0F41 0044 0056 0046 0052 0054 0053  ...A.D.V.F.R.T.S
0056 0052 0002 0012 0041 0044 0056 0046  .V.R.....A.D.V.F
0052 0054 0053 0056 0052 0001 001A 0041  .R.T.S.V.R.....A
0046 004E 0056 004D 0049 0053 0043 0046  .F.N.V.M.I.S.C.F
0049 004C 0045 0053 0004 003C 0061 0064  .I.L.E.S...<.a.d
0076 0066 0072 0074 0073 0076 0072 002E  .v.f.r.t.s.v.r..
0061 0064 0076 0061 006E 0074 0061 0067  .a.d.v.a.n.t.a.g
0065 0066 0072 0065 0069 0067 0068 0074  .e.f.r.e.i.g.h.t
002E 0063 006F 006D 0003 0058 0041 0046  ...c.o.m...X.A.F
004E 0056 004D 0049 0053 0043 0046 0049  .N.V.M.I.S.C.F.I
004C 0045 0053 002E 0061 0064 0076 0066  .L.E.S...a.d.v.f
0072 0074 0073 0076 0072 002E 0061 0064  .r.t.s.v.r...a.d
0076 0061 006E 0074 0061 0067 0065 0066  .v.a.n.t.a.g.e.f
0072 0065 0069 0067 0068 0074 002E 0063  .r.e.i.g.h.t...c
006F 006D 0005 003C 0061 0064 0076 0066  .o.m...<.a.d.v.f
0072 0074 0073 0076 0072 002E 0061 0064  .r.t.s.v.r...a.d
0076 0061 006E 0074 0061 0067 0065 0066  .v.a.n.t.a.g.e.f
0072 0065 0069 0067 0068 0074 002E 0063  .r.e.i.g.h.t...c
006F 006D 0007 0008 001C E420 B646 4ED1  .o.m....... .FN.
0100 0000 00 .....

background.js:6524 Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 22…}
background.js:6524 Asn1Obj {tag_: 161, value_: null, children_: Array[1]}
background.js:6531 Response OID = 1.3.6.1.4.1.311.2.2.10
background.js:6531 NTLMSSP_NEGOTIATE_UNICODE: true
background.js:6531 NTLMSSP_NEGOTIATE_OEM: false
background.js:6531 NTLMSSP_REQUEST_TARGET: true
background.js:6531 NTLMSSP_NEGOTIATE_SIGN: true
background.js:6531 NTLMSSP_NEGOTIATE_SEAL: false
background.js:6531 NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
background.js:6531 NTLMSSP_NEGOTIATE_LM_KEY: false
background.js:6531 NTLMSSP_NEGOTIATE_NETWARE: false
background.js:6531 NTLMSSP_NEGOTIATE_NTLM: true
background.js:6531 NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
background.js:6531 NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
background.js:6531 NTLMSSP_NEGOTIATE_LOCAL_CALL: false
background.js:6531 NTLMSSP_NEGOTIATE_ALWAYS_SIGN: true
background.js:6531 NTLMSSP_TARGET_TYPE_DOMAIN: true
background.js:6531 NTLMSSP_TARGET_TYPE_SERVER: false
background.js:6531 NTLMSSP_TARGET_TYPE_SHARE: false
background.js:6531 NTLMSSP_NEGOTIATE_NTLM2_KEY: true
background.js:6531 NTLMSSP_REQUEST_INIT_RESPONSE: false
background.js:6531 NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
background.js:6531 NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
background.js:6531 NTLMSSP_NEGOTIATE_TARGET_INFO: true
background.js:6531 NTLMSSP_NEGOTIATE_128: true
background.js:6531 NTLMSSP_NEGOTIATE_KEY_EXCH: false
background.js:6531 NTLMSSP_NEGOTIATE_56: false
background.js:6531 Use LMv2 and NTLMv2 because LMCompatibilityLevel=5
background.js:6524 Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}
background.js:6524 SessionSetupRequest {types_: Types, flags_: 0, securityMode_: 1, capabilities_: 1, channel_: 0…}
background.js:6524 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 582, packetHelper_: PacketHelper}
background.js:6517 writePacket
background.js:6524 FE53 4D42 4000 0100 0000 0000 0100 0100  .SMB@...........
0000 0000 0000 0000 0300 0000 0000 0000  ................
BECB 0000 0000 0000 6100 003C 0004 0000  ........a..<....
0000 0000 0000 0000 0000 0000 0000 0000  ................
1900 0001 0100 0000 0000 0000 5800 EE01  ............X...
0000 0000 0000 0000 A182 01EA 3082 01E6  ............0...
A282 01E2 0482 01DE 4E54 4C4D 5353 5000  ........NTLMSSP.
0300 0000 1800 1800 4000 0000 5001 5001  ........@...P.P.
5800 0000 1200 1200 A801 0000 1400 1400  X...............
BA01 0000 1000 1000 CE01 0000 0000 0000  ................
0000 0000 0102 0000 E5A5 82F0 9E7C 57A2  .............|W.
837D 8450 9DE0 A1D3 33D1 CAF4 9B44 886F  .}.P....3....D.o
3CC1 F8CD 972F 490D 8967 E2EE A12A 4542  <..../I..g...*EB
0101 0000 0000 0000 E082 0BB6 464E D101  ............FN..
12C3 86CB 1F00 0000 0000 0000 0200 1200  ................
4100 4400 5600 4600 5200 5400 5300 5600  A.D.V.F.R.T.S.V.
5200 0100 1A00 4100 4600 4E00 5600 4D00  R.....A.F.N.V.M.
4900 5300 4300 4600 4900 4C00 4500 5300  I.S.C.F.I.L.E.S.
0400 3C00 6100 6400 7600 6600 7200 7400  ..<.a.d.v.f.r.t.
7300 7600 7200 2E00 6100 6400 7600 6100  s.v.r...a.d.v.a.
6E00 7400 6100 6700 6500 6600 7200 6500  n.t.a.g.e.f.r.e.
6900 6700 6800 7400 2E00 6300 6F00 6D00  i.g.h.t...c.o.m.
0300 5800 4100 4600 4E00 5600 4D00 4900  ..X.A.F.N.V.M.I.
5300 4300 4600 4900 4C00 4500 5300 2E00  S.C.F.I.L.E.S...
6100 6400 7600 6600 7200 7400 7300 7600  a.d.v.f.r.t.s.v.
7200 2E00 6100 6400 7600 6100 6E00 7400  r...a.d.v.a.n.t.
6100 6700 6500 6600 7200 6500 6900 6700  a.g.e.f.r.e.i.g.
6800 7400 2E00 6300 6F00 6D00 0500 3C00  h.t...c.o.m...<.
6100 6400 7600 6600 7200 7400 7300 7600  a.d.v.f.r.t.s.v.
7200 2E00 6100 6400 7600 6100 6E00 7400  r...a.d.v.a.n.t.
6100 6700 6500 6600 7200 6500 6900 6700  a.g.e.f.r.e.i.g.
6800 7400 2E00 6300 6F00 6D00 0700 0800  h.t...c.o.m.....
1CE4 20B6 464E D101 0000 0000 0000 0000  .. .FN..........
6100 6400 7600 6600 7200 7400 7300 7600  a.d.v.f.r.t.s.v.
7200 6100 6400 6D00 6900 6E00 2D00 6500  r.a.d.m.i.n.-.e.
7200 6900 6B00 4600 5300 5000 5F00 4300  r.i.k.F.S.P._.C.
4900 4600 5300  I.F.S.

background.js:6517 readPacket
background.js:6517 _readPacketSize
background.js:6517 _readPacketSize - 2
background.js:6517 readPacket: 73
background.js:6524 FE53 4D42 4000 0100 6D00 00C0 0100 0100  .SMB@...m.......
0100 0000 0000 0000 0300 0000 0000 0000  ................
BECB 0000 0000 0000 6100 003C 0004 0000  ........a..<....
0000 0000 0000 0000 0000 0000 0000 0000  ................
0900 0000 0000 0000 00 .........

**Comment by yoichiro** [comment]
@erikolsonAFN Probably, the server you wanted to mount needs a signature for all requests. Because, the server returned 'true' for two configurations regarding a signing:

```
background.js:6531 NTLMSSP_NEGOTIATE_SIGN: true
...
background.js:6531 NTLMSSP_NEGOTIATE_ALWAYS_SIGN: true
```

The current version of this app doesn't support the signing feature. Could you confirm that the server needs the signature to communicate to each client?

**Comment by dougwantstoknow** [comment]
Has anyone figured this out? I am experiencing the same issue, NT_STATUS_LOGON_FAILURE trying to connect to a Windows 7 share and a Server 2012 share.  

One strange thing I see is on the Mount a new Windows file server diaglog box.  Once I enter all the information and click KEEP, on the left window I see the IP address and port of the server and then beneath that in parenthesis, I see my authentication listed as domain@username instead of username@domain.  Is that right?

From what I can see on these posts, everybody is sending in logs and then there is no response.  Can anyone help?

Thanks

**Comment by erikolsonAFN** [comment]
No I just checked and we do not require a signature.  Also this was working
for us about a month ago.  I do not know if the app has been updated since
then though.

Thanks,

On Mon, Jan 18, 2016 at 6:21 AM, Yoichiro Tanaka notifications@github.com
wrote:

> @erikolsonAFN https://github.com/erikolsonAFN Probably, the server you
> wanted to mount needs a signature for all requests. Because, the server
> returned 'true' for two configurations regarding a signing:
> 
> background.js:6531 NTLMSSP_NEGOTIATE_SIGN: true
> ...
> background.js:6531 NTLMSSP_NEGOTIATE_ALWAYS_SIGN: true
> 
> The current version of this app doesn't support the signing feature. Could
> you confirm that the server needs the signature to communicate to each
> client?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yoichiro/chromeos-filesystem-cifs/issues/175#issuecomment-172513708
> .

## 

_Erik Olson_
_Systems Administrator_
AFN joins the Transport Topics list of Top 25 Brokerage Firms! Learn more
here.
http://www.loadafn.com/afn-news/afn-joins-the-transport-topics-2015-top-25-brokerage-firms/

_7230 N. Caldwell Ave._

_Niles__, IL   60714_

_Direct Phone / Direct Fax: *_224-515-7326*

_Website: http://www.loadafn.com http://www.afnww.com/_

**Comment by erikolsonAFN** [comment]
We found a solution.  We needed to change the LMCompatability setting.  It defaults to 5 I believe and we changed it to 1.  Anyone else may need to experiment with which one is best for them and their environment but 1 worked for us.

Thanks!
