### ISSUE TITLE
Adding an address that can't be found causes the application to get stuck

### ISSUE THREAD

**Issue by ghost** [yoichiro/chromeos-filesystem-cifs#18]
When I try to add a host IP it seems that if it cant connect to it I am unable to press the `MOUNT` button after entering a different IP. I have to close the app and re-open it.

**Comment by yoichiro** [comment]
@brycethorup Thank you for the reporting. I have just released the new version to fix this issue. For instance, the diff was... https://github.com/yoichiro/chromeos-filesystem-cifs/pull/21 Could you confirm whether this issue is solved or not by using the new version?

**Comment by yoichiro** [comment]
@brycethorup I close this issue, because you could not feedback here, that is, I think that this issue was solved. If you have same issue again, you can re-open this issue. Thank you for this reporting.

**Comment by ghost** [comment]
@yoichiro sorry for the delay. It seems to be handling it correctly now. No more hang-ups. Thanks.

**Comment by yoichiro** [comment]
@brycethorup Good. :)
