### ISSUE TITLE
Some operations are taking longer than expected.  Do you want to abort them?

### ISSUE THREAD

**Issue by dnikkel** [yoichiro/chromeos-filesystem-cifs#19]
I'm experiencing the same problem with the SMB provider that I had with the WEBDAV provider.  When I'm streaming music from my Synology NAS, I get a steady stream of system messages popping up saying, "Some operations are taking longer than expected.  Do you want to abort them?"  However, the streaming does not have any detectable dropouts when this happens.

In one case, I did have playback freeze, but it was immediately after coming back to my computer after it had had time to spin down.  Could be the NAS didn't quite have its act together after spinning up again.

As with the WEBDAV provider, the log contents don't indicate there was an issue, I have an on-going stream of log messages in the following pattern:

onReadFileRequested - start
background.js:12939 Object {fileSystemId: "cifsfs://192.168.1.229:445/dave", length: 524288, offset: 0, openRequestId: 3784, requestId: 3786}
background.js:12950 Object {data: ArrayBuffer, hasMore: false}
background.js:12672 TaskQueue: consumeTask - queue: empty
background.js:12655 TaskQueue: addTask - Call consume task: length=1
background.js:12665 TaskQueue: consumeTask - execute task: length=1

**Comment by yoichiro** [comment]
@dnikkel Hmm... Sorry, I don't know the reason to cause this issue... Did this situation occur frequently?

**Comment by dnikkel** [comment]
Yesterday, when I reported the problem, it was happening constantly - as soon as I dismissed the pop up message, another would appear. So, let's say, more than once a minute.  However, right now, I've been streaming for over 10 minutes and it hasn't happened yet.  So it's definitely inconsistent.

**Comment by yoichiro** [comment]
@dnikkel Hmm... I close this issue. If you have same problem again, please create a new issue to report it to me. Thanks!

**Comment by dnikkel** [comment]
No problem.  The inconsistency is very puzzling, I'll try to include more actionable details if I reopen it.
