### ISSUE TITLE
Windows File Server - Can Not Connect

### ISSUE THREAD

**Issue by scre80** [yoichiro/chromeos-filesystem-cifs#20]
Hi, 

Firstly, very excited. We at our company have been waiting for this app to come. 

I am trying to connect to a particular share on our Windows File Server. All I see is attempting to mount and then there is no error or connection. 

Can you please confirm if this app is enterprise ready yet? as in can connect ton Win 2003 / 2008 servers with domain credentials? I also tried a standard Win 7 PC and also had the same issue. 

Thanks

**Comment by icebun** [comment]
I have the same problem.

I have trying to connect to a WIndows 2003 File Server on a Domain.

The error I am getting is as folllows:_

3221225581

NT_STATUS_LOGON_FAILURE

**Comment by scre80** [comment]
Hi, 

I got it working on my NAS at home straight away, just in our Windows AD environment I can not get it working. Has anyone been able to get this working?

Thanks
Scott

**Comment by bjkluft** [comment]
I use a windows home server 2011 and get the following error:
net::ERR_NAME_NOT_RESOLVED
Please can you help?

**Comment by scre80** [comment]
I finally got it to connect to a Win 7 pc. I had to setup a local account and make sure the share was not Hidden. 

Will support for Hidden shares and LDAP be coming?

**Comment by yoichiro** [comment]
@scre80 @bjkluft @icebun Thank you for the reporting. In the current version, Domain authentication not supported. I just registered this issue #28. I close this issue.

**Comment by scre80** [comment]
Thankyou. Do you have hidden shares logged as well?

**Comment by yoichiro** [comment]
@scre80 Sorry, what is meaning "hidden"?

**Comment by scre80** [comment]
Any windows device that has a share with a $ at the end, is hidden and needs to be known explicitly. Most enterprises use this to some extent. 

Some more information here
https://support.microsoft.com/en-us/kb/314984
