### ISSUE TITLE
tomato share

### ISSUE THREAD

**Issue by to0w1r3d** [yoichiro/chromeos-filesystem-cifs#22]
Cannot mount smb share on tomato router - cifs1/2 no authentication

**Comment by yoichiro** [comment]
@to0w1r3d I cannot find the reason, because the information you reported was very little. Could you confirm the debug console log by using the following steps?
https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by yoichiro** [comment]
@to0w1r3d I close this issue, because you didn't provide enough information to solve this issue. You can re-open this, if you get same issue with the latest version. Thank you for the reporting.
