### ISSUE TITLE
Need method to pass mount options; in particular sec=ntlm

### ISSUE THREAD

**Issue by rbraby** [yoichiro/chromeos-filesystem-cifs#27]
In general, it would be good to have a method to pass mount options to this extension.  In particular, there are a number of older SMB servers which only support ntlm or ntlmv2 security, which means they need sec=ntlm or sec=ntlm2 as a mount option.

I've encountered this issue using disks shared from an Apple Airport Extreme (802.11N version).

Without sec=ntlm, the error encountered is:
NT_STATUS_NOT_IMPLEMENTED

**Comment by yoichiro** [comment]
@rbraby I have a question. Does the Apple Airport Extreme support ntlm only? In current version of my app, actually the NTLMv2 is applied, and NTLM(v1) not used. I think that NTLMv1 has a security problem, therefore, I thought that NTLMv1 should not be used... How do you think about that?

**Comment by rbraby** [comment]
@yoichiro, I think you are correct and the Airport Extreme (at least the older model I have) is only supporting NTLM(v1).  I did some further testing with sec=ntlmv2 and sec=ntlmssp and both failed with a NT_STATUS_LOGON_FAILURE.

I'm sure NTLMv2 and NTLMSSP are more secure, but for backwards compatibility it would be nice for there to be a way to enable the older protocol.

**Comment by yoichiro** [comment]
@rbraby I see. I'll try to support them (LM and NTLNv1). Please give me a few days.

**Comment by yoichiro** [comment]
Diff to solve this issue: #31. The points are:
- If the server doesn't support NTLMv2, the server should return false as NTLMSSP_NEGOTIATE_NTLM2 flag.
- When the flag value was false, my application sends LMv1 and NTLMv1 responses.

**Comment by yoichiro** [comment]
@rbraby I have just released the new version 1.1.4 including the code to fix this issue as #31. Could you confirm whether this issue is solved or not on your environment?

**Comment by rbraby** [comment]
I rebooted my chromebook to ensure the extension was updated, and verified that I am running version 1.1.4 by checking chrome://extensions.  Unfortunately, when I try to mount the drive from my airport extreme, I still get NT_STATUS_NOT_IMPLEMENTED and a failure to mount.  I wonder if the airport extreme is failing to properly respond to the NTLM version negotiation.

**Comment by yoichiro** [comment]
@rbraby I just released the new version 1.1.5. In this version, you can change the log level. After updating it to 1.1.5, click the gear icon, and change the log level to "Trace". Then, try to mount your server. Last, confirm the output log by the following steps:
https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools
Probably, you can see the NTLMSSP_NEGOTIATE flag set. I want to know the all flag values, and error messages if occurred.

**Comment by rbraby** [comment]
![screenshot 2015-06-05 at 11 03 37 pm](https://cloud.githubusercontent.com/assets/5756165/8018050/84524da8-0bd7-11e5-80b8-b8076386e188.png)

I'm fairly new to Chrome and it's console logs.  Hopefully I expanded the pieces of the logs that you need.  If not, please let me know and I'll try again.

Thanks,
Ryan

**Comment by yoichiro** [comment]
@rbraby Were the rows all in the console tab?

**Comment by rbraby** [comment]
I noticed version 1.1.7 was out, so I updated to it, and here's the console output from this new version.  The error returned is still NT_STATUS_NOT_IMPLEMENTED.

![screenshot 2015-06-06 at 10 13 35 pm](https://cloud.githubusercontent.com/assets/5756165/8022355/7b621f80-0c99-11e5-9ff9-9a0c3619b252.png)

**Comment by rbraby** [comment]
I noticed that version 1.1.7 had been released, so I upgraded to it, and tried again.  Here is the console output from that attempt (missing initial Object{type: "getSharedResources", . . .} line).  The error returned is still NT_STATUS_NOT_IMPLEMENTED.
![screenshot 2015-06-06 at 10 18 04 pm](https://cloud.githubusercontent.com/assets/5756165/8022363/586a9916-0c9a-11e5-89a2-caddc1880870.png)

**Comment by yoichiro** [comment]
@rbraby Sorry, my application does not support servers which don't support EXTENDED_SECURITY. Also, I don't intend to support it in near future.
