### ISSUE TITLE
Not Compatible!?

### ISSUE THREAD

**Issue by ds679** [yoichiro/chromeos-filesystem-cifs#30]
Tried to install tonight on my Toshiba CB35-B3340 and received this:

![screenshot 2015-06-04 at 22 25 20](https://cloud.githubusercontent.com/assets/6852706/7998892/a95b6604-0b08-11e5-9023-1637cafbd3f9.png)

**Comment by ds679** [comment]
Welp....to answer my own issue (maybe it'll help others).  I had a ChromeOS update that needed to complete first (which would then bring my Chrome Version to 42+).  After updating, worked like a charm - thanks

**Comment by yoichiro** [comment]
Good. I close this issue. Thanks!
