### ISSUE TITLE
Can not mount folder on Windows 2012 R2

### ISSUE THREAD

**Issue by AndreyLavrov** [yoichiro/chromeos-filesystem-cifs#41]
I have tested SMB ver. 1.1.8 on Windows 7 (Standalone) and Windows 2008 R2 (Member) succesfully.
Unfortunaly the same test was failed on Windows Server 2012 R2 (Member).
SMB app failed when I click "Mount" button with following messages (see picture below):
Top left - Files.app (front-end)
Top right - Files.app (backgroud)
Bottom left - SMB (front-end)
Bottom right - SMB (background)

My Chrome version: 
Version 43.0.2357.81 (64-bit)
Platform 6946.55.0 (Official Build) stable-channel monroe
Firmware Google_Monroe.4921.17.0

My Window Server 2012 R2 version:
Windows Server 2012 R2 Datacenter Edition
Member server with a "clear" dedicated network adapter for SMB access (no Teaming, no NLB, no Cluster Heartbeat, no VM Network).

![smb - windows 2012 r2 - mount error](https://cloud.githubusercontent.com/assets/12710354/8023930/e2a9cd56-0d29-11e5-9c8d-2133633a6089.png)

**Comment by yoichiro** [comment]
@AndreyLavrov Hmm, I guess that your Windows 2012 server disconnected the connection immediately without returning any response. That is, my application can't know the reason... Could you check the server's log of Windows 2012 server side?

**Comment by AndreyLavrov** [comment]
I have enabled all windows logs (services logs included) and saved all events.
Any access (success or deny) from a test Windows client to server SMB folder is logged but when I mounted the same SMB folder from Chromebook then event were not logged.
I captured a network traffic from Chromebook (192.168.1.101) to Windows Server (192.168.1.5) (see picture below). May be it helps.
![network traffic](https://cloud.githubusercontent.com/assets/12710354/8024743/facf1342-0d46-11e5-9be4-5a1986617737.png)

**Comment by AndreyLavrov** [comment]
I carefully inspected a configuration for Datacenter and found that CIFS protocol was been disabled by a corporate security policy however SMB v.1 was been enabled and monitored by management system successfully. 
After that I enabled CIFS in my test environment and successfully mount SMB folder on Windows Server 2012 R2.
It is great that SMB/CIFS app can work with Windows 2012 R2 and I think that this issue could be closed.
I attach a screenshot with a configuration for SMB on Windows Server 2012 that works (see picture below).
P.S. It is important that those cmdlets have some bugs therefore it is recomended to reinstall "SMB 1.0/CIFS File Sharing Support" feature and restart server to access SMB folder.
P.P.S. It is a great app but for security reasons it could not be used in production environment before it will support SMB v.3 and domain authentication.

![get-smbserverconfiguration](https://cloud.githubusercontent.com/assets/12710354/8057021/5c4b2b9a-0eb6-11e5-89c6-51cfb856b787.png)
