### ISSUE TITLE
Mapping Share to WinVista Box

### ISSUE THREAD

**Issue by bluecrema** [yoichiro/chromeos-filesystem-cifs#44]
I am struggling to map a share to a windows vista box (yes I know why vista .. long story).  I keep getting the same error (2147483653: UNKNOWN).  Windows Log shows that authentication is successful.  I was able to map successfully to a Windows 7 box I have with no problem.

Hoping you can assist.

Chrome OS:
Version 44.0.2403.33 beta (64-bit)
Platform 7077.27.0 (Official Build) beta-channel swanky
Firmware Google_Swanky.5216.238.5

Console Log:
Object {type: "getSharedResources", serverName: "20.0.0.14", serverPort: "445", username: "mike", password: "XXXXXXXXX"}
background.js:6157 Client#login
background.js:6157 connect
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 47}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 115
background.js:6171 CAP_EXTENDED_SECURITY: true
background.js:6171 CAP_COMPRESSED_DATA: false
background.js:6171 CAP_BULK_TRANSFER: false
background.js:6171 CAP_UNIX: false
background.js:6171 CAP_LARGE_WRITEX: true
background.js:6171 CAP_LARGE_READX: true
background.js:6171 CAP_INFOLEVEL_PASSTHROUGH: true
background.js:6171 CAP_DFS: false
background.js:6171 CAP_NT_FIND: true
background.js:6171 CAP_LOCK_AND_READ: true
background.js:6171 CAP_LEVEL_II_OPLOCKS: true
background.js:6171 CAP_STATUS32: true
background.js:6171 CAP_RPC_REMOTE_APIS: true
background.js:6171 CAP_NT_SMBS: true
background.js:6171 CAP_LARGE_FILES: true
background.js:6171 CAP_UNICODE: true
background.js:6171 CAP_MPX_MODE: false
background.js:6171 CAP_RAW_MODE: true
background.js:6164 Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
background.js:6164 NegotiateProtocolResponse {types_: Types, dialectIndex_: 0, securityMode_: 3, maxMpxCount_: 10, maxNumberVCs_: 1…}
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 160}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 377
background.js:6171 NTLMSSP_NEGOTIATE_UNICODE: true
background.js:6171 NTLMSSP_NEGOTIATE_OEM: false
background.js:6171 NTLMSSP_REQUEST_TARGET: true
background.js:6171 NTLMSSP_NEGOTIATE_SIGN: false
background.js:6171 NTLMSSP_NEGOTIATE_SEAL: false
background.js:6171 NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
background.js:6171 NTLMSSP_NEGOTIATE_LM_KEY: false
background.js:6171 NTLMSSP_NEGOTIATE_NETWARE: false
background.js:6171 NTLMSSP_NEGOTIATE_NTLM: true
background.js:6171 NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
background.js:6171 NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
background.js:6171 NTLMSSP_NEGOTIATE_LOCAL_CALL: false
background.js:6171 NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
background.js:6171 NTLMSSP_TARGET_TYPE_DOMAIN: false
background.js:6171 NTLMSSP_TARGET_TYPE_SERVER: true
background.js:6171 NTLMSSP_TARGET_TYPE_SHARE: false
background.js:6171 NTLMSSP_NEGOTIATE_NTLM2: true
background.js:6171 NTLMSSP_REQUEST_INIT_RESPONSE: false
background.js:6171 NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
background.js:6171 NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
background.js:6171 NTLMSSP_NEGOTIATE_TARGET_INFO: true
background.js:6171 NTLMSSP_NEGOTIATE_128: true
background.js:6171 NTLMSSP_NEGOTIATE_KEY_EXCH: false
background.js:6171 NTLMSSP_NEGOTIATE_56: false
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 370}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 219
background.js:6157 Client#getSharedResourceList
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 84}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 48
background.js:6164 Header {types_: Types, protocol_: "SMB", command_: 117, errorClass_: 0, errorCode_: 0…}
background.js:6164 TreeConnectAndxResponse {types_: Types, responseUtils_: ResponseUtils, supportSearchBits_: true, shareIsInDfs_: false, service_: "IPC"}
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 100}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 135
background.js:6164 Header {types_: Types, protocol_: "SMB", command_: 162, errorClass_: 0, errorCode_: 0…}
background.js:6164 NtCreateAndxResponse {types_: Types, responseUtils_: ResponseUtils, opLockLevel_: 0, fid: null, createDisposition_: 1…}
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 154}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 1148
background.js:6164 Header {types_: Types, protocol_: "SMB", command_: 37, errorClass_: 0, errorCode_: 0…}
background.js:6164 DceRpcBindAck {types_: Types, dceRpc_: DceRpc, ackResult_: 0}
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 174}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 2104
background.js:11846 2147483653: UNKNOWN

**Comment by yoichiro** [comment]
@bluecrema Could you confirm whether you can reproduce this issue with the latest version?

**Comment by bluecrema** [comment]
@yoichiro Thanks for looking in to this.

I am updated to 1.4.0 now and I still get the same error 2147483653: UNKNOWN

Here is my console log:

background.js:6157 Object {type: "getSharedResources", serverName: "20.0.0.14", serverPort: "445", username: "mike", password: "XXXXXXXX"}
background.js:6157 Client#login
background.js:6171 Domain name not specified. '?' will be applied.
background.js:6157 connect
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 47}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 115
background.js:6171 CAP_EXTENDED_SECURITY: true
background.js:6171 CAP_COMPRESSED_DATA: false
background.js:6171 CAP_BULK_TRANSFER: false
background.js:6171 CAP_UNIX: false
background.js:6171 CAP_LARGE_WRITEX: true
background.js:6171 CAP_LARGE_READX: true
background.js:6171 CAP_INFOLEVEL_PASSTHROUGH: true
background.js:6171 CAP_DFS: false
background.js:6171 CAP_NT_FIND: true
background.js:6171 CAP_LOCK_AND_READ: true
background.js:6171 CAP_LEVEL_II_OPLOCKS: true
background.js:6171 CAP_STATUS32: true
background.js:6171 CAP_RPC_REMOTE_APIS: true
background.js:6171 CAP_NT_SMBS: true
background.js:6171 CAP_LARGE_FILES: true
background.js:6171 CAP_UNICODE: true
background.js:6171 CAP_MPX_MODE: false
background.js:6171 CAP_RAW_MODE: true
background.js:6171 NEGOTIATE_SECURITY_SIGNATURES_REQUIRED: 0
background.js:6171 NEGOTIATE_SECURITY_SIGNATURES_ENABLED: 0
background.js:6171 NEGOTIATE_SECURITY_CHALLENGE_RESPONSE: 1
background.js:6171 NEGOTIATE_SECURITY_USER_LEVEL: 1
background.js:6164 Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
background.js:6164 NegotiateProtocolResponse {types_: Types, dialectIndex_: 0, securityMode_: 3, maxMpxCount_: 10, maxNumberVCs_: 1…}
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 160}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 377
background.js:6164 Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 22, errorCode_: 49152…}
background.js:6171 NTLMSSP_NEGOTIATE_UNICODE: true
background.js:6171 NTLMSSP_NEGOTIATE_OEM: false
background.js:6171 NTLMSSP_REQUEST_TARGET: true
background.js:6171 NTLMSSP_NEGOTIATE_SIGN: false
background.js:6171 NTLMSSP_NEGOTIATE_SEAL: false
background.js:6171 NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
background.js:6171 NTLMSSP_NEGOTIATE_LM_KEY: false
background.js:6171 NTLMSSP_NEGOTIATE_NETWARE: false
background.js:6171 NTLMSSP_NEGOTIATE_NTLM: true
background.js:6171 NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
background.js:6171 NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
background.js:6171 NTLMSSP_NEGOTIATE_LOCAL_CALL: false
background.js:6171 NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
background.js:6171 NTLMSSP_TARGET_TYPE_DOMAIN: false
background.js:6171 NTLMSSP_TARGET_TYPE_SERVER: true
background.js:6171 NTLMSSP_TARGET_TYPE_SHARE: false
background.js:6171 NTLMSSP_NEGOTIATE_NTLM2: true
background.js:6171 NTLMSSP_REQUEST_INIT_RESPONSE: false
background.js:6171 NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
background.js:6171 NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
background.js:6171 NTLMSSP_NEGOTIATE_TARGET_INFO: true
background.js:6171 NTLMSSP_NEGOTIATE_128: true
background.js:6171 NTLMSSP_NEGOTIATE_KEY_EXCH: false
background.js:6171 NTLMSSP_NEGOTIATE_56: false
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 370}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 219
background.js:6157 Client#getSharedResourceList
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 84}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 48
background.js:6164 Header {types_: Types, protocol_: "SMB", command_: 117, errorClass_: 0, errorCode_: 0…}
background.js:6164 TreeConnectAndxResponse {types_: Types, responseUtils_: ResponseUtils, supportSearchBits_: true, shareIsInDfs_: false, service_: "IPC"}
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 100}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 135
background.js:6164 Header {types_: Types, protocol_: "SMB", command_: 162, errorClass_: 0, errorCode_: 0…}
background.js:6164 NtCreateAndxResponse {types_: Types, responseUtils_: ResponseUtils, opLockLevel_: 0, fid: null, createDisposition_: 1…}
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 154}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 1148
background.js:6164 Header {types_: Types, protocol_: "SMB", command_: 37, errorClass_: 0, errorCode_: 0…}
background.js:6164 DceRpcBindAck {types_: Types, dceRpc_: DceRpc, ackResult_: 0}
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 174}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 2104
background.js:12001 2147483653: UNKNOWN

**Comment by bluecrema** [comment]
@yoichiro I saw the update to 1.4.2 and updated and the issue is resolved now.  I am able to map to my Vista drives now.  GREAT JOB!!! Thanks for this great extension!
