### ISSUE TITLE
Mounting of remote folder results in UNKNOWN

### ISSUE THREAD

**Issue by VitaZalud** [yoichiro/chromeos-filesystem-cifs#45]
Hallo, I have similar issue like https://github.com/yoichiro/chromeos-filesystem-cifs/issues/16 is.

When, I try to connect my shared folder, it results with 2147483653: UNKNOWN, which is exactly the same statement like in #16 

My Chrmoe OS is 43
Version 43.0.2357.81
Platform 6946.55.0 (Official Build) stable-channel nyan_blaze
Firmware Google_Nyan_Blaze.5771.63.0

Console log is here (password stared here, but correct in reality).

Object {type: "getSharedResources", serverName: "deer", serverPort: "445", username: "zalud", password: "******"}
background.js:6157 Client#login
background.js:6157 connect
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 47}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 205
background.js:6171 CAP_EXTENDED_SECURITY: true
background.js:6171 CAP_COMPRESSED_DATA: false
background.js:6171 CAP_BULK_TRANSFER: false
background.js:6171 CAP_UNIX: false
background.js:6171 CAP_LARGE_WRITEX: true
background.js:6171 CAP_LARGE_READX: true
background.js:6171 CAP_INFOLEVEL_PASSTHROUGH: true
background.js:6171 CAP_DFS: false
background.js:6171 CAP_NT_FIND: true
background.js:6171 CAP_LOCK_AND_READ: true
background.js:6171 CAP_LEVEL_II_OPLOCKS: true
background.js:6171 CAP_STATUS32: true
background.js:6171 CAP_RPC_REMOTE_APIS: true
background.js:6171 CAP_NT_SMBS: true
background.js:6171 CAP_LARGE_FILES: true
background.js:6171 CAP_UNICODE: true
background.js:6171 CAP_MPX_MODE: false
background.js:6171 CAP_RAW_MODE: false
background.js:6164 Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
background.js:6164 NegotiateProtocolResponse {types_: Types, dialectIndex_: 0, securityMode_: 3, maxMpxCount_: 50, maxNumberVCs_: 1…}
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 160}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 445
background.js:6171 NTLMSSP_NEGOTIATE_UNICODE: true
background.js:6171 NTLMSSP_NEGOTIATE_OEM: false
background.js:6171 NTLMSSP_REQUEST_TARGET: true
background.js:6171 NTLMSSP_NEGOTIATE_SIGN: false
background.js:6171 NTLMSSP_NEGOTIATE_SEAL: false
background.js:6171 NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
background.js:6171 NTLMSSP_NEGOTIATE_LM_KEY: false
background.js:6171 NTLMSSP_NEGOTIATE_NETWARE: false
background.js:6171 NTLMSSP_NEGOTIATE_NTLM: true
background.js:6171 NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
background.js:6171 NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
background.js:6171 NTLMSSP_NEGOTIATE_LOCAL_CALL: false
background.js:6171 NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
background.js:6171 NTLMSSP_TARGET_TYPE_DOMAIN: true
background.js:6171 NTLMSSP_TARGET_TYPE_SERVER: false
background.js:6171 NTLMSSP_TARGET_TYPE_SHARE: false
background.js:6171 NTLMSSP_NEGOTIATE_NTLM2: true
background.js:6171 NTLMSSP_REQUEST_INIT_RESPONSE: false
background.js:6171 NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
background.js:6171 NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
background.js:6171 NTLMSSP_NEGOTIATE_TARGET_INFO: true
background.js:6171 NTLMSSP_NEGOTIATE_128: true
background.js:6171 NTLMSSP_NEGOTIATE_KEY_EXCH: false
background.js:6171 NTLMSSP_NEGOTIATE_56: false
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 438}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 219
background.js:6157 Client#getSharedResourceList
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 104}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 48
background.js:6164 Header {types_: Types, protocol_: "SMB", command_: 117, errorClass_: 0, errorCode_: 0…}
background.js:6164 TreeConnectAndxResponse {types_: Types, responseUtils_: ResponseUtils, supportSearchBits_: true, shareIsInDfs_: false, service_: "IPC"}
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 100}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 135
background.js:6164 Header {types_: Types, protocol_: "SMB", command_: 162, errorClass_: 0, errorCode_: 0…}
background.js:6164 NtCreateAndxResponse {types_: Types, responseUtils_: ResponseUtils, opLockLevel_: 0, fid: null, createDisposition_: 1…}
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 154}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 1148
background.js:6164 Header {types_: Types, protocol_: "SMB", command_: 37, errorClass_: 0, errorCode_: 0…}
background.js:6164 DceRpcBindAck {types_: Types, dceRpc_: DceRpc, ackResult_: 0}
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 194}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 2104
background.js:11846 2147483653: UNKNOWN

**Comment by yoichiro** [comment]
```
background.js:6171 NTLMSSP_TARGET_TYPE_DOMAIN: true
```

@VitaZalud The current version doesn't support Domain Authentication. Please see #28. I close this issue.
