### ISSUE TITLE
Extended security not supported

### ISSUE THREAD

**Issue by stoniu** [yoichiro/chromeos-filesystem-cifs#46]
Hello,

This is real great addon for ChromeOS but sadly I'm getting this message when I'm trying to connect to my Asus RT-N66U router NAS. My version is 1.1.8

![screenshot 2015-06-08 at 8 21 20 pm](https://cloud.githubusercontent.com/assets/12805524/8048413/00702bbe-0e1f-11e5-976a-84a2643d2fa1.png)

Thank you.

**Comment by yoichiro** [comment]
@stoniu Unfortunately, I don't intend to support servers which don't support the Extended Security, because I guess that the number of such servers is very little. But, I created a ticker #48. If many comments posted against the ticket, I'll fix this issue. Thank you for the reporting.
