### ISSUE TITLE
Support Un-extended security connection

### ISSUE THREAD

**Issue by yoichiro** [yoichiro/chromeos-filesystem-cifs#48]
As the title. If your server doesn't support the "Extended Security", you will face the error message "Extended security not supported". Currently, I intend not to support servers which don't support the extended security. But, if you want to mount such server, please leave a comment here. When many comments posted, I'll implement this feature.

**Comment by hvdwolf** [comment]
This has to do with the security settings in the smb.conf
You get this error if you set "security = share" (deprecated as of samba >3.0).

If you set the security to  "security = user", which is the default anyway, you will not get this error message.

**Comment by p-chom** [comment]
I also have this issue when trying to connect to an Apple Time Capsule. I can't change any of the SMB security settings on the Time Capsule (except password) so this extension can't connect to it. It throws the same "Extended security not supported" error that other users report. Is there any way to disable this requirement? Even just for local network shares?

**Comment by yoichiro** [comment]
I intend to release a new version including the following authentications:
- For "share" mode.
- For "un-extended security" and "challenge-response".

The diff for them is #54.

**Comment by yoichiro** [comment]
I just have released the new version 1.3.0 including codes to fix this issue.

**Comment by stoniu** [comment]
Thank you very much for this fix man! I was waiting for it...
You are a genius!

**Comment by yoichiro** [comment]
@stoniu Haha, thanks.

**Comment by yoichiro** [comment]
I close this issue.
