### ISSUE TITLE
Files.app was crushed after write operations in LocalUser mode

### ISSUE THREAD

**Issue by AndreyLavrov** [yoichiro/chromeos-filesystem-cifs#50]
SMB/CIFS app (ver. 1.2.0) can succesfully mount SMB folders for Domain Users Accounts as well as for Local Users Accounts.
In a folder which is mounted for domain user account all works fine.
If you try to delete and/or edit files in a folder  which is mounted for local user account then tose operations are completed in most cases but Files.app will crushed and Error Message will appeare: 

SMB/CIFS File System
5963778: UNKNOWN

![mount 1 2 0](https://cloud.githubusercontent.com/assets/12710354/8100930/8ee1d166-101a-11e5-9cd5-6c2ac6dff1a0.png)

**Comment by AndreyLavrov** [comment]
Steps to reproduce:
1) Mount SMB folder by local user account in SMB/CIFS app
2) Tap SMB folder in Files app (some errors in Files.app occur (see below) but all working fine for a user)
3) (On Chromebook) Create/Edit/Delete a single file. All works fine.
4) (On Windows Client) Create a subfolder "Images" and copy 9 images into it. All works fine but the folder did not refreshed on Chromebook.
5) (On Chromebook) Close Files.app and launch it again. (Images folder and their content appeared in Chromebook)
6) Tap  "Images" folder in Files.app (Result: see on picture 1)
7) Press "Trash" icon in Files.app (Result: see picture 2)
8) Press "Delete" button on confirmation dialog. (Result: see picture 3)
Files.app stalled after deleting 3 files only.
Error messages flashed from a SMB app.

Picture 1-3:
Top left - Files.app
Top right - SMB background console
Bottom left - Files.app front-end console
Bottom right - Files.app background console

Picture 4 (SMB error context):
Top left - Files.app
Middle left - Files.app front-end console
Bottom left - Files.app background console
Right - SMB background console scrolled up to the first error

Picture 5 - SMB "background" console is filtered by "Error" filter

---

Picture 1 - Images in SMB folder were shown

## ![1 - image folder open](https://cloud.githubusercontent.com/assets/12710354/8102912/9efede42-102c-11e5-957b-c37d8d5530ac.png)

---

Picture 2 - Confirmation dialog is shown

## ![2 - delete confirmation](https://cloud.githubusercontent.com/assets/12710354/8102921/ad12c76e-102c-11e5-94db-d89ce8c91bc6.png)

---

Picture 3 - Files.app stalled after delete 3 files only

## ![3 - files app crushed after 3 images were deleted](https://cloud.githubusercontent.com/assets/12710354/8102927/b7a07262-102c-11e5-95f3-33224062efd9.png)

---

Picture 4 - SMB background console is scrolled to show fisrt error

## ![4 - smb background console is showed first error](https://cloud.githubusercontent.com/assets/12710354/8102931/bd45fba6-102c-11e5-8752-992981be0126.png)

---

Picture 5 - SMB background console (Full errors list)

## ![5 - full error list - 10 errors filtered](https://cloud.githubusercontent.com/assets/12710354/8102934/c4e7100c-102c-11e5-80b4-c4613db85026.png)

**Comment by yoichiro** [comment]
@AndreyLavrov Well, I could reproduce this issue. I will investigate this reason and fix this.

**Comment by yoichiro** [comment]
@AndreyLavrov I just fixed this issue at https://github.com/yoichiro/chromeos-filesystem-cifs/commit/a6f1dab587580c481a81fc726aca7c448f197222. Could you check whether this issue is fixed by the diff?

**Comment by AndreyLavrov** [comment]
Great work!
SMB ver.1.2.1 don't crush Files.app!
If a user don't look into a console then user experience is good (see picture 1).

![5 - final test complete](https://cloud.githubusercontent.com/assets/12710354/8115099/bf217220-1081-11e5-8585-0dfb19d8dc29.png)

SMB app passed "delete images test" successfully but have many errors in SMB background console as well as Files.app console (see pictures below).

![1 - image folder](https://cloud.githubusercontent.com/assets/12710354/8115103/c8fbcb24-1081-11e5-90dd-4e57ba672704.png)

![2 - delete confirm](https://cloud.githubusercontent.com/assets/12710354/8115107/d050c622-1081-11e5-81e3-107c560febf9.png)

![3 - operation complete](https://cloud.githubusercontent.com/assets/12710354/8115111/d6e450f8-1081-11e5-9791-afd7a2f59b5c.png)

![4 - errors summary](https://cloud.githubusercontent.com/assets/12710354/8115115/dc3646ec-1081-11e5-80af-28678617b9e9.png)

**Comment by yoichiro** [comment]
@AndreyLavrov Big thanks! I will release the new version as 1.2.0 today.

**Comment by yoichiro** [comment]
@AndreyLavrov I have just released the version 1.2.0. If this issue is reproduced at 1.2.0, please reopen this issue. Thank you for this reporting!
