### ISSUE TITLE
FSP key which is included into manifest.json is not supported

### ISSUE THREAD

**Issue by AndreyLavrov** [yoichiro/chromeos-filesystem-cifs#51]
Step to reproduce:
1) Install SMB/CIFS ver.1.2.0
2) Look at the "Extensions" tab in Chrome browser.

![manifest warning](https://cloud.githubusercontent.com/assets/12710354/8101592/42f263cc-1021-11e5-8a31-32267666a317.png)

**Comment by yoichiro** [comment]
@AndreyLavrov Which version is your ChromeOS? If 43, its manifest key is not supported yet, but it is supported from 44+, I think.

**Comment by AndreyLavrov** [comment]
## My Chrome version:

Version 43.0.2357.81 (64-bit)
Platform 6946.55.0 (Official Build) stable-channel monroe
Firmware Google_Monroe.4921.17.0

**Comment by yoichiro** [comment]
@AndreyLavrov Thank you for the checking. Yes, the warning message will not be shown after you update your ChromeOS to the version 44 (My ChromeOS Beta Channel 44 doesn't show the warning message). I close this issue.
