### ISSUE TITLE
SMB app could refresh file list periodically in a current folder.

### ISSUE THREAD

**Issue by AndreyLavrov** [yoichiro/chromeos-filesystem-cifs#52]
While folder used concurrently then chromebook's users don't see changes from other users.
Windows Explorer updates file list in a current folder periodically to improve user experience. I think SMB app could do the same thing for SMB folders.

**Comment by yoichiro** [comment]
@AndreyLavrov Yes, I already know this behavior. Well, the current version continues to have a file list permanently, and doesn't have an expiration mechanism. Also, the Files app doesn't have a UI to refresh/reload the file list. Well, I try to add the expiration logic. Please give me a few days to implement that.

**Comment by yoichiro** [comment]
@AndreyLavrov Well, I was mis-understanding. At least, my app reloads a file list everytime. when some directory is selected. That is, if a new file was added into a folder, when the user selects other folder and re-selects the folder again, the new file will be shown. However, if the user doesn't operate this step, the new file cannot be shown.

I guess that this issue cannot be solved without improvement of Files.app...for example, adding a refresh button to reload a file list, or firing onReadDirectoryRequested event periodically and automatically by the Files.app... At least, The loaded file list cannot be updated from FSP implementation, I think.

I intend to post this proposal to crbug.

**Comment by yoichiro** [comment]
@AndreyLavrov I file this issue to the crbug: https://code.google.com/p/chromium/issues/detail?id=500775

**Comment by yoichiro** [comment]
I received a comment against the filed issue above. In Dev Channel of ChromeOS, three new APIs were added. Probably, I will be able to fix this issue, but I don't know how to use them... I'm investigating the way to use them now.

**Comment by yoichiro** [comment]
@AndreyLavrov The current versio of ChromeOS is providing a function to refresh a file list. Close this issue.
