### ISSUE TITLE
Mounting a section "Network" (or similar) to the Files app and show the search results as folders

### ISSUE THREAD

**Issue by KevinBLT** [yoichiro/chromeos-filesystem-cifs#61]
Hello,

I think it would be easier for many users to see a section "Network" on the left panel of the Files.app.
When selecting it, you could show the search results as folders and when clicking on them open its content or request the login (but then ask for saving the login data).

This would grant similar behaviour to this extension as expected from other operating systems.

Greets
Kevin

**Comment by yoichiro** [comment]
@KevinBLT I think that such feature cannot be developed by each FSP app. Please report the proposal to crbug (https://code.google.com/p/chromium/issues/list).
