### ISSUE TITLE
Unable to connect to share with no credentials.

### ISSUE THREAD

**Issue by qwerty017** [yoichiro/chromeos-filesystem-cifs#68]
I have a share on a seagate black armor nas and am allowing Public/anonymous use but am unable to connect to it. I keep getting bad username/password errors. Is it possible to log in anonymously using your app?

**Comment by yoichiro** [comment]
@qwerty017 Could you confirm the debug log by this steps https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools and put it here? I would like to know the situation more detail.

**Comment by qwerty017** [comment]
Below is with no username or password entered and then with username and password being anonymous.

Object {type: "getSharedResources", serverName: "sbanas", serverPort: "445", username: "", password: ""…}
background.js:6160 Client#login
background.js:6174 Domain name not specified. '?' will be applied.
background.js:6160 connect
background.js:6167 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 47}
background.js:6160 writePacket
background.js:6160 readPacket
background.js:6160 _readPacketSize
background.js:6160 _readPacketSize - 2
background.js:6160 readPacket: 127
background.js:6174 CAP_EXTENDED_SECURITY: true
background.js:6174 CAP_COMPRESSED_DATA: false
background.js:6174 CAP_BULK_TRANSFER: false
background.js:6174 CAP_UNIX: false
background.js:6174 CAP_LARGE_WRITEX: true
background.js:6174 CAP_LARGE_READX: true
background.js:6174 CAP_INFOLEVEL_PASSTHROUGH: true
background.js:6174 CAP_DFS: true
background.js:6174 CAP_NT_FIND: true
background.js:6174 CAP_LOCK_AND_READ: true
background.js:6174 CAP_LEVEL_II_OPLOCKS: true
background.js:6174 CAP_STATUS32: true
background.js:6174 CAP_RPC_REMOTE_APIS: true
background.js:6174 CAP_NT_SMBS: true
background.js:6174 CAP_LARGE_FILES: true
background.js:6174 CAP_UNICODE: true
background.js:6174 CAP_MPX_MODE: false
background.js:6174 CAP_RAW_MODE: false
background.js:6174 NEGOTIATE_SECURITY_SIGNATURES_REQUIRED: 0
background.js:6174 NEGOTIATE_SECURITY_SIGNATURES_ENABLED: 1
background.js:6174 NEGOTIATE_SECURITY_CHALLENGE_RESPONSE: 1
background.js:6174 NEGOTIATE_SECURITY_USER_LEVEL: 1
background.js:6167 Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
background.js:6167 NegotiateProtocolResponse {types_: Types, dialectIndex_: 0, securityMode_: 7, maxMpxCount_: 50, maxNumberVCs_: 1…}
background.js:6167 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 160}
background.js:6160 writePacket
background.js:6160 readPacket
background.js:6160 _readPacketSize
background.js:6160 _readPacketSize - 2
background.js:6160 readPacket: 254
background.js:6167 Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 22, errorCode_: 49152…}
background.js:6174 NTLMSSP_NEGOTIATE_UNICODE: true
background.js:6174 NTLMSSP_NEGOTIATE_OEM: false
background.js:6174 NTLMSSP_REQUEST_TARGET: true
background.js:6174 NTLMSSP_NEGOTIATE_SIGN: false
background.js:6174 NTLMSSP_NEGOTIATE_SEAL: false
background.js:6174 NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
background.js:6174 NTLMSSP_NEGOTIATE_LM_KEY: false
background.js:6174 NTLMSSP_NEGOTIATE_NETWARE: false
background.js:6174 NTLMSSP_NEGOTIATE_NTLM: true
background.js:6174 NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
background.js:6174 NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
background.js:6174 NTLMSSP_NEGOTIATE_LOCAL_CALL: false
background.js:6174 NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
background.js:6174 NTLMSSP_TARGET_TYPE_DOMAIN: false
background.js:6174 NTLMSSP_TARGET_TYPE_SERVER: true
background.js:6174 NTLMSSP_TARGET_TYPE_SHARE: false
background.js:6174 NTLMSSP_NEGOTIATE_NTLM2: true
background.js:6174 NTLMSSP_REQUEST_INIT_RESPONSE: false
background.js:6174 NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
background.js:6174 NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
background.js:6174 NTLMSSP_NEGOTIATE_TARGET_INFO: true
background.js:6174 NTLMSSP_NEGOTIATE_128: true
background.js:6174 NTLMSSP_NEGOTIATE_KEY_EXCH: false
background.js:6174 NTLMSSP_NEGOTIATE_56: false
background.js:6167 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 368}
background.js:6160 writePacket
background.js:6160 readPacket
background.js:6160 _readPacketSize
background.js:6160 _readPacketSize - 2
background.js:6160 readPacket: 100
background.js:6160 Client#getSharedResourceList
background.js:6167 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 78}
background.js:6160 writePacket
background.js:6160 readPacket
background.js:6160 _readPacketSize
background.js:6160 _readPacketSize - 2
background.js:6160 readPacket: 35
background.js:12011 3221225506: NT_STATUS_ACCESS_DENIED

background.js:6160 Object {type: "getSharedResources", serverName: "sbanas", serverPort: "445", username: "anonymous", password: "anonymous"…}
background.js:6160 Client#login
background.js:6174 Domain name not specified. '?' will be applied.
background.js:6160 connect
background.js:6167 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 47}
background.js:6160 writePacket
background.js:6160 readPacket
background.js:6160 _readPacketSize
background.js:6160 _readPacketSize - 2
background.js:6160 readPacket: 127
background.js:6174 CAP_EXTENDED_SECURITY: true
background.js:6174 CAP_COMPRESSED_DATA: false
background.js:6174 CAP_BULK_TRANSFER: false
background.js:6174 CAP_UNIX: false
background.js:6174 CAP_LARGE_WRITEX: true
background.js:6174 CAP_LARGE_READX: true
background.js:6174 CAP_INFOLEVEL_PASSTHROUGH: true
background.js:6174 CAP_DFS: true
background.js:6174 CAP_NT_FIND: true
background.js:6174 CAP_LOCK_AND_READ: true
background.js:6174 CAP_LEVEL_II_OPLOCKS: true
background.js:6174 CAP_STATUS32: true
background.js:6174 CAP_RPC_REMOTE_APIS: true
background.js:6174 CAP_NT_SMBS: true
background.js:6174 CAP_LARGE_FILES: true
background.js:6174 CAP_UNICODE: true
background.js:6174 CAP_MPX_MODE: false
background.js:6174 CAP_RAW_MODE: false
background.js:6174 NEGOTIATE_SECURITY_SIGNATURES_REQUIRED: 0
background.js:6174 NEGOTIATE_SECURITY_SIGNATURES_ENABLED: 1
background.js:6174 NEGOTIATE_SECURITY_CHALLENGE_RESPONSE: 1
background.js:6174 NEGOTIATE_SECURITY_USER_LEVEL: 1
background.js:6167 Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
background.js:6167 NegotiateProtocolResponse {types_: Types, dialectIndex_: 0, securityMode_: 7, maxMpxCount_: 50, maxNumberVCs_: 1…}
background.js:6167 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 160}
background.js:6160 writePacket
background.js:6160 readPacket
background.js:6160 _readPacketSize
background.js:6160 _readPacketSize - 2
background.js:6160 readPacket: 254
background.js:6167 Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 22, errorCode_: 49152…}
background.js:6174 NTLMSSP_NEGOTIATE_UNICODE: true
background.js:6174 NTLMSSP_NEGOTIATE_OEM: false
background.js:6174 NTLMSSP_REQUEST_TARGET: true
background.js:6174 NTLMSSP_NEGOTIATE_SIGN: false
background.js:6174 NTLMSSP_NEGOTIATE_SEAL: false
background.js:6174 NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
background.js:6174 NTLMSSP_NEGOTIATE_LM_KEY: false
background.js:6174 NTLMSSP_NEGOTIATE_NETWARE: false
background.js:6174 NTLMSSP_NEGOTIATE_NTLM: true
background.js:6174 NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
background.js:6174 NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
background.js:6174 NTLMSSP_NEGOTIATE_LOCAL_CALL: false
background.js:6174 NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
background.js:6174 NTLMSSP_TARGET_TYPE_DOMAIN: false
background.js:6174 NTLMSSP_TARGET_TYPE_SERVER: true
background.js:6174 NTLMSSP_TARGET_TYPE_SHARE: false
background.js:6174 NTLMSSP_NEGOTIATE_NTLM2: true
background.js:6174 NTLMSSP_REQUEST_INIT_RESPONSE: false
background.js:6174 NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
background.js:6174 NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
background.js:6174 NTLMSSP_NEGOTIATE_TARGET_INFO: true
background.js:6174 NTLMSSP_NEGOTIATE_128: true
background.js:6174 NTLMSSP_NEGOTIATE_KEY_EXCH: false
background.js:6174 NTLMSSP_NEGOTIATE_56: false
background.js:6167 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 386}
background.js:6160 writePacket
background.js:6160 readPacket
background.js:6160 _readPacketSize
background.js:6160 _readPacketSize - 2
background.js:6160 readPacket: 100
background.js:6160 Client#getSharedResourceList
background.js:6167 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 78}
background.js:6160 writePacket
background.js:6160 readPacket
background.js:6160 _readPacketSize
background.js:6160 _readPacketSize - 2
background.js:6160 readPacket: 35
background.js:12011 3221225506: NT_STATUS_ACCESS_DENIED

**Comment by qwerty017** [comment]
Are there any other logs you require?

**Comment by yoichiro** [comment]
@qwerty017 Hmm... I don't know the reason why your server returned the access_denied error. Basically, my app cannot get more detail information except the error code. That is, I guess that you need to investigate your server's log. Could you find any error logs in your server's log?

**Comment by qwerty017** [comment]
I will check my NAS and see if I can get any logs from it.

**Comment by yoichiro** [comment]
@qwerty017 Could you give me information you collected?

**Comment by qwerty017** [comment]
Unfortunately, I do not see any way to get logs from the NAS.

**Comment by yoichiro** [comment]
@qwerty017 Hmm... Sorry, I guess that I cannot fix this issue. I close this issue, and please re-open or post an issue as new, after you can get some information. Thanks.
