### ISSUE TITLE
error "Some operations are taking longer than exprected. Do you want to abort them?"

### ISSUE THREAD

**Issue by helpguy** [yoichiro/chromeos-filesystem-cifs#69]
The first time I connected perfectly. Mounted my connection just fine.
The second time, I get this error. (see screenshot)

Any idea what I did wrong?

Acer C740 Chromebook.

![screenshot 2015-06-26 at 3 50 36 pm](https://cloud.githubusercontent.com/assets/13071269/8388993/836f8a5c-1c1e-11e5-826d-ec8c10914b81.png)

**Comment by yoichiro** [comment]
@helpguy Could you confirm a debug log on the console tab of the DevTools by using this steps? https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by yoichiro** [comment]
@helpguy I close this issue, because you didn't provide any information to fix your issue to me. If you can get some logs, please re-open this issue or create a new issue. Thanks.

**Comment by unextro** [comment]
Hi @yoichiro, getting the same error message... Here's the log:

connect
Header
NegotiateProtocolRequest
Packet
CAP_EXTENDED_SECURITY: true
CAP_COMPRESSED_DATA: false
CAP_BULK_TRANSFER: false
CAP_UNIX: false
CAP_LARGE_WRITEX: true
CAP_LARGE_READX: true
CAP_INFOLEVEL_PASSTHROUGH: false
CAP_DFS: true
CAP_NT_FIND: true
CAP_LOCK_AND_READ: true
CAP_LEVEL_II_OPLOCKS: true
CAP_STATUS32: true
CAP_RPC_REMOTE_APIS: true
CAP_NT_SMBS: true
CAP_LARGE_FILES: true
CAP_UNICODE: true
CAP_MPX_MODE: false
CAP_RAW_MODE: true
NEGOTIATE_SECURITY_SIGNATURES_REQUIRED: 0
NEGOTIATE_SECURITY_SIGNATURES_ENABLED: 0
NEGOTIATE_SECURITY_CHALLENGE_RESPONSE: 1
NEGOTIATE_SECURITY_USER_LEVEL: 1
Header
NegotiateProtocolResponse
Header
SessionSetupAndxRequest
Packet
Header
NTLMSSP_NEGOTIATE_UNICODE: true
NTLMSSP_NEGOTIATE_OEM: false
NTLMSSP_REQUEST_TARGET: true
NTLMSSP_NEGOTIATE_SIGN: false
NTLMSSP_NEGOTIATE_SEAL: false
NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
NTLMSSP_NEGOTIATE_LM_KEY: false
NTLMSSP_NEGOTIATE_NETWARE: false
NTLMSSP_NEGOTIATE_NTLM: true
NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
NTLMSSP_NEGOTIATE_LOCAL_CALL: false
NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
NTLMSSP_TARGET_TYPE_DOMAIN: true
NTLMSSP_TARGET_TYPE_SERVER: false
NTLMSSP_TARGET_TYPE_SHARE: false
NTLMSSP_NEGOTIATE_NTLM2: true
NTLMSSP_REQUEST_INIT_RESPONSE: false
NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
NTLMSSP_NEGOTIATE_TARGET_INFO: true
NTLMSSP_NEGOTIATE_128: true
NTLMSSP_NEGOTIATE_KEY_EXCH: false
NTLMSSP_NEGOTIATE_56: false
Header
SessionSetupAndxRequest
Packet
Header
TreeConnectAndxRequest
Packet
Header
TreeConnectAndxResponse
Resumed file system: cifsfs://czchonsnas2:445/PRG-DC@mdejnozk/mdejnozk$
Header
EmptyRequest
Packet
Header
LogoffAndxRequest
Header
disconnect
Unchecked runtime.lastError while running fileSystemProviderInternal.operationRequestedSuccess: NOT_FOUND
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:13633:17)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:13651:25)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:13656:29)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:14037:21)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:12052:21)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:12371:13)
connect
Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
NegotiateProtocolRequest {types_: Types, dialects: Array[0], dialects_: Array[1]}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 47}
CAP_EXTENDED_SECURITY: true
CAP_COMPRESSED_DATA: false
CAP_BULK_TRANSFER: false
CAP_UNIX: false
CAP_LARGE_WRITEX: true
CAP_LARGE_READX: true
CAP_INFOLEVEL_PASSTHROUGH: false
CAP_DFS: true
CAP_NT_FIND: true
CAP_LOCK_AND_READ: true
CAP_LEVEL_II_OPLOCKS: true
CAP_STATUS32: true
CAP_RPC_REMOTE_APIS: true
CAP_NT_SMBS: true
CAP_LARGE_FILES: true
CAP_UNICODE: true
CAP_MPX_MODE: false
CAP_RAW_MODE: true
NEGOTIATE_SECURITY_SIGNATURES_REQUIRED: 0
NEGOTIATE_SECURITY_SIGNATURES_ENABLED: 0
NEGOTIATE_SECURITY_CHALLENGE_RESPONSE: 1
NEGOTIATE_SECURITY_USER_LEVEL: 1
Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
NegotiateProtocolResponse {types_: Types, dialectIndex_: 0, securityMode_: 3, maxMpxCount_: 50, maxNumberVCs_: 1…}
Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 0, errorCode_: 0…}
SessionSetupAndxRequest {types_: Types, maxBufferSize_: 33028, maxMpxCount_: 50, vcNumber_: 1, sessionKey_: 762549197…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 160}
Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 22, errorCode_: 49152…}
NTLMSSP_NEGOTIATE_UNICODE: true
NTLMSSP_NEGOTIATE_OEM: false
NTLMSSP_REQUEST_TARGET: true
NTLMSSP_NEGOTIATE_SIGN: false
NTLMSSP_NEGOTIATE_SEAL: false
NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
NTLMSSP_NEGOTIATE_LM_KEY: false
NTLMSSP_NEGOTIATE_NETWARE: false
NTLMSSP_NEGOTIATE_NTLM: true
NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
NTLMSSP_NEGOTIATE_LOCAL_CALL: false
NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
NTLMSSP_TARGET_TYPE_DOMAIN: true
NTLMSSP_TARGET_TYPE_SERVER: false
NTLMSSP_TARGET_TYPE_SHARE: false
NTLMSSP_NEGOTIATE_NTLM2: true
NTLMSSP_REQUEST_INIT_RESPONSE: false
NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
NTLMSSP_NEGOTIATE_TARGET_INFO: true
NTLMSSP_NEGOTIATE_128: true
NTLMSSP_NEGOTIATE_KEY_EXCH: false
NTLMSSP_NEGOTIATE_56: false
Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 0, errorCode_: 0…}
SessionSetupAndxRequest {types_: Types, maxBufferSize_: 33028, maxMpxCount_: 50, vcNumber_: 1, sessionKey_: 762549197…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 434}
Header {types_: Types, protocol_: "SMB", command_: 117, errorClass_: 0, errorCode_: 0…}
TreeConnectAndxRequest {types_: Types, path_: "\czchonsnas2\MDEJNOZK$", service_: "?????"}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 98}
Header {types_: Types, protocol_: "SMB", command_: 117, errorClass_: 0, errorCode_: 0…}
TreeConnectAndxResponse {types_: Types, responseUtils_: ResponseUtils, supportSearchBits_: true, shareIsInDfs_: false, service_: "A:"}
Header {types_: Types, protocol_: "SMB", command_: 50, errorClass_: 0, errorCode_: 0…}
TransactionRequest {types_: Types, transactionName_: null, flags_: 0, timeout_: 0, parameter_: Object…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 76}
Header {types_: Types, protocol_: "SMB", command_: 50, errorClass_: 0, errorCode_: 0…}
QueryPathInfoResponse {types_: Types, responseUtils_: ResponseUtils, file_: File}
onReadDirectoryRequested Object {directoryPath: "/", fileSystemId: "cifsfs://czchonsnas2:445/PRG-DC@mdejnozk/mdejnozk$", requestId: 2}
Header {types_: Types, protocol_: "SMB", command_: 50, errorClass_: 0, errorCode_: 0…}
TransactionRequest {types_: Types, transactionName_: null, flags_: 0, timeout_: 0, parameter_: Object…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 86}
Error in event handler for sockets.tcp.onReceive: RangeError: Offset is outside the bounds of the DataView
    at Types.getFixed4BytesValue (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:6610:27)
    at ResponseUtils.loadData (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:8123:47)
    at loadData (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:10026:43)
    at FindFirst2Response.load (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:9985:18)
    at Protocol.parseFindFirst2ResponsePacket (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:11210:28)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:12687:44)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:11539:21)
    at ChromeSocket2.fetch (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:11767:26)
    at ChromeSocket2.fetch (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:11769:26)
