### ISSUE TITLE
apple airport extreme drive sharing issue

### ISSUE THREAD

**Issue by 100khz** [yoichiro/chromeos-filesystem-cifs#75]
I am able to search for drives shared on apple router and they get mounted fine. But no files are accessible. it gives an error on chromebook that  3221225530 - nt-status-path-not-found

**Comment by yoichiro** [comment]
@100khz Could you confirm the debug log on the console tab of the DevTools by this steps? https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by yoichiro** [comment]
@100khz I close this issue, because you didn't provide any information to fix your issue to me. If you can get some logs, please re-open this issue or create a new issue. Thanks.
