### ISSUE TITLE
writing to CIFS has problems near 2GB into the file

### ISSUE THREAD

**Issue by dkewley** [yoichiro/chromeos-filesystem-cifs#76]
Initially discussed in issue #64. Still seen in extension version 1.4.5.

I'm using this extension to write a file that is slightly larger than 2GB. The write process seems to proceed properly until about the 2GB mark, then problems arise. The symptoms seem to include a hole being written into the target file, as if a seek was being done far into the file. The resulting file has a length much longer than the source file, and in first case below, I confirmed that the file has a hole. (The amount of actual data in that target file is approximately the same as the source file.)

When writing 2GB file from ChromeOS to Synology DS213j NAS, the file appears to be written just fine until about the 2GB mark, at which point the file suddenly goes from ~2GB in size to ~6GB in size. I've confirmed with `debugfs` in the embedded Linux environment on the NAS that the file has a hole from near the 2GB mark to near the 6GB mark. So the number of blocks written is about right, but there are zero blocks stored from about 2GB to about 6GB. It's as if the write process did a seek from the 2GB point to the 6GB then continued writing.

This NAS runs Samba 4.1.18. This NAS appears to have a 32-bit processor, FWIW.

I then tested against a Windows 7 target instead of the NAS. In Windows Explorer, the file seemed to get written steadily up to about the 2GB mark, then there was a brief pause (seconds), then the file size was reported as slightly less than 3.5GB, again as if a seek was done far into the file, leaving the hole. In this case I also observed that the copy process in the Files app in ChromeOS did not report the file copy as having completed -- the copy progress notification just hung there in the File app with a nearly complete progress bar. Clicking the X to stop the copy appeared not to work.

The target in this case is 64-bit Windows 7.

Since very similar behavior was observed when copying to two different targets running very different CIFS services (including 64-bit Windows), I do not believe that the problem lies on the target side. I believe the problem is likely either in this extension or in some aspect of ChromeOS.

@yoichiro : Does it work for you to copy files of size >2GB?

Thank you very much for this extension and for spending time responding to issue reports and attempting fixes!

**Comment by yoichiro** [comment]
@dkewley Sorry, actually I tested the reading file case only. I intend to test the writing file situation and try to reproduce this issue on my environment. Please give me a few days. I will post a comment, if I can find something about this issue.

**Comment by dkewley** [comment]
Thank you @yoichiro! I took some time to look over the source, and it looks like a fix for this issue would be to apply a change to RequestUtils.prototype.divide8BytesValue similar to what you did in the previous fix for Types.prototype.setFixed8BytesValue.

**Comment by yoichiro** [comment]
@dkewley Oh, thank you for the investigating! Probably, yeah, it is the cause...

**Comment by yoichiro** [comment]
@dkewley I have just released a new version 1.4.6 which has a modification #77 to solve this issue. Could you confirm whether you cannot reproduce this issue by ugin 1.4.6?

**Comment by dkewley** [comment]
@yoichiro I have tested v1.4.6 of your extension, copying the same file (slightly larger than 2GB) to the same NAS, and this time the target file has size 2GB as expected, instead of the previous failure (where the file appeared to be 6GB, and had a large hole in it).

I have not re-tested against my 64-bit Windows 7 target, but I have no reason to think it would fail, given that it worked against this NAS (running Samba, with apparently a 32-bit processor).

Thank you for the fix, it appears to have solved the problem!

**Comment by yoichiro** [comment]
@dkewley My pleasure!
