### ISSUE TITLE
Connection hangs

### ISSUE THREAD

**Issue by mattiyeh** [yoichiro/chromeos-filesystem-cifs#78]
Hello -

I am trying to mount a shared windows folder on my chromebook. When I input the wrong server/username/password/domain, the program gives me an appropriate error message stating NT_STATUS_LOGON_FAILURE. However, when I input the correct parameters and click MOUNT, it seems to hang. I get no error message and no sign that a connection is established. I just get "Attempting to mount instance..." and that's it. I took a look in the console and have attached the contents below.

A few things I noticed:
There are two instances of a Header object that contain error codes. By converting the ntstyleerrorcode to hex and referring to [this table from MSDN](https://msdn.microsoft.com/en-us/library/ee441884.aspx), I find that both error codes point to STATUS_BUFFER_OVERFLOW 0x80000005 and STATUS_MORE_PROCESSING_REQUIRED 0xC0000016.

Can you explain why this is happening?

Thank you,
Marc

```
Object {type: "getSharedResources", serverName: "SERVNAME", serverPort: "445", username: "UNAME", password: "PWORD"}domainName: "DNAME"password: "PWORD"serverName: "SERVNAME"serverPort: "445"type: "getSharedResources"username: "UNAME"__proto__: Object
Client#login
connect
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 47}dataLength_: 47data_: ArrayBuffertypes_: Types__proto__: Packet
writePacket
readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 188
CAP_EXTENDED_SECURITY: true
CAP_COMPRESSED_DATA: false
CAP_BULK_TRANSFER: false
CAP_UNIX: false
CAP_LARGE_WRITEX: true
CAP_LARGE_READX: true
CAP_INFOLEVEL_PASSTHROUGH: true
CAP_DFS: false
CAP_NT_FIND: true
CAP_LOCK_AND_READ: false
CAP_LEVEL_II_OPLOCKS: true
CAP_STATUS32: true
CAP_RPC_REMOTE_APIS: true
CAP_NT_SMBS: true
CAP_LARGE_FILES: true
CAP_UNICODE: true
CAP_MPX_MODE: false
CAP_RAW_MODE: false
NEGOTIATE_SECURITY_SIGNATURES_REQUIRED: 0
NEGOTIATE_SECURITY_SIGNATURES_ENABLED: 0
NEGOTIATE_SECURITY_CHALLENGE_RESPONSE: 1
NEGOTIATE_SECURITY_USER_LEVEL: 1
Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0}command_: 114errorClass_: 0errorCode_: 0flag2_: 51202flag_: 152multiplexId_: 1ntStyleErrorCode_: 0processId_: 2protocol_: "SMB"treeId_: 0types_: TypesuserId_: 0__proto__: Header
NegotiateProtocolResponse {types_: Types, dialectIndex_: 0, securityMode_: 3, maxMpxCount_: 80, maxNumberVCs_: 1}capabilities_: 2147541756dialectIndex_: 0domainName_: ""encryptionKeyLength_: 0encryptionKey_: Array[0]guid_: Uint8Array[16]maxBufferSize_: 16384maxMpxCount_: 80maxNumberVCs_: 1maxRawSize_: 65536securityBlob_: Uint8Array[102]securityMode_: 3serverTimeZone_: 0sessionKey_: 0systemTimeHigh_: 30456460systemTimeLow_: 1148067840types_: Types__proto__: NegotiateProtocolResponse
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 160}dataLength_: 160data_: ArrayBuffertypes_: Types__proto__: Packet
writePacket
readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 290
Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 22, errorCode_: 49152}command_: 115errorClass_: 22errorCode_: 49152flag2_: 51202flag_: 152multiplexId_: 2ntStyleErrorCode_: 3221225494processId_: 2protocol_: "SMB"treeId_: 0types_: TypesuserId_: 1__proto__: Header
NTLMSSP_NEGOTIATE_UNICODE: true
NTLMSSP_NEGOTIATE_OEM: false
NTLMSSP_REQUEST_TARGET: true
NTLMSSP_NEGOTIATE_SIGN: false
NTLMSSP_NEGOTIATE_SEAL: false
NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
NTLMSSP_NEGOTIATE_LM_KEY: false
NTLMSSP_NEGOTIATE_NETWARE: false
NTLMSSP_NEGOTIATE_NTLM: true
NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
NTLMSSP_NEGOTIATE_LOCAL_CALL: false
NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
NTLMSSP_TARGET_TYPE_DOMAIN: true
NTLMSSP_TARGET_TYPE_SERVER: false
NTLMSSP_TARGET_TYPE_SHARE: false
NTLMSSP_NEGOTIATE_NTLM2: true
NTLMSSP_REQUEST_INIT_RESPONSE: false
NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
NTLMSSP_NEGOTIATE_TARGET_INFO: true
NTLMSSP_NEGOTIATE_128: true
NTLMSSP_NEGOTIATE_KEY_EXCH: false
NTLMSSP_NEGOTIATE_56: false
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 440}dataLength_: 440data_: ArrayBuffertypes_: Types__proto__: Packet
writePacket
readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 82
Client#getSharedResourceList
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 78}dataLength_: 78data_: ArrayBuffertypes_: Types__proto__: Packet
writePacket
readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 48
Header {types_: Types, protocol_: "SMB", command_: 117, errorClass_: 0, errorCode_: 0}command_: 117errorClass_: 0errorCode_: 0flag2_: 51202flag_: 152multiplexId_: 4ntStyleErrorCode_: 0processId_: 2protocol_: "SMB"treeId_: 1types_: TypesuserId_: 1__proto__: Header
TreeConnectAndxResponse {types_: Types, responseUtils_: ResponseUtils, supportSearchBits_: false, shareIsInDfs_: false, service_: "IPC"}responseUtils_: ResponseUtilstypes_: Types__proto__: ResponseUtilsservice_: "IPC"shareIsInDfs_: falsesupportSearchBits_: falsetypes_: Types__proto__: TreeConnectAndxResponse
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 100}dataLength_: 100data_: ArrayBuffertypes_: Types__proto__: Packet
writePacket
readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 135
Header {types_: Types, protocol_: "SMB", command_: 162, errorClass_: 0, errorCode_: 0}command_: 162errorClass_: 0errorCode_: 0flag2_: 51202flag_: 152multiplexId_: 5ntStyleErrorCode_: 0processId_: 2protocol_: "SMB"treeId_: 1types_: TypesuserId_: 1__proto__: Header
NtCreateAndxResponse {types_: Types, responseUtils_: ResponseUtils, opLockLevel_: 0, fid: null, createDisposition_: 1}allocationSize_: 8192createDisposition_: 1createTime_: Sun Dec 31 1600 19:00:00 GMT-0500 (EST)directory_: 0endOfFile_: 0extFileAttributes_: 128fid: nullfid_: 1lastAccessTime_: Sun Dec 31 1600 19:00:00 GMT-0500 (EST)lastChangeTime_: Sun Dec 31 1600 19:00:00 GMT-0500 (EST)lastWriteTime_: Sun Dec 31 1600 19:00:00 GMT-0500 (EST)nmPipeStatus_: 1535opLockLevel_: 0resourceType_: 2responseUtils_: ResponseUtilstypes_: Types__proto__: NtCreateAndxResponse
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 154}dataLength_: 154data_: ArrayBuffertypes_: Types__proto__: Packet
writePacket
readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 124
Header {types_: Types, protocol_: "SMB", command_: 37, errorClass_: 0, errorCode_: 0}command_: 37errorClass_: 0errorCode_: 0flag2_: 51202flag_: 152multiplexId_: 6ntStyleErrorCode_: 0processId_: 2protocol_: "SMB"treeId_: 1types_: TypesuserId_: 1__proto__: Header
DceRpcBindAck {types_: Types, dceRpc_: DceRpc, ackResult_: 0}ackResult_: 0dceRpc_: DceRpctypes_: Types__proto__: DceRpcBindAck
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 170}dataLength_: 170data_: ArrayBuffertypes_: Types__proto__: Packet
writePacket
readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 1080
Header {types_: Types, protocol_: "SMB", command_: 37, errorClass_: 5, errorCode_: 32768}command_: 37errorClass_: 5errorCode_: 32768flag2_: 51202flag_: 152multiplexId_: 7ntStyleErrorCode_: 2147483653processId_: 2protocol_: "SMB"treeId_: 1types_: TypesuserId_: 1__proto__: Header
writePacket
readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 3132
Header {types_: Types, protocol_: "SMB", command_: 46, errorClass_: 0, errorCode_: 0}command_: 46errorClass_: 0errorCode_: 0flag2_: 51202flag_: 152multiplexId_: 8ntStyleErrorCode_: 0processId_: 2protocol_: "SMB"treeId_: 1types_: TypesuserId_: 1__proto__: Header
ReadAndxResponse {types_: Types, responseUtils_: ResponseUtils, available_: 0, dataCompactionMode_: 0, dataLength_: 3072}available_: 0dataCompactionMode_: 0dataLength_: 3072data_: Uint8Array[3072]responseUtils_: ResponseUtilstypes_: Types__proto__: ReadAndxResponse
writePacket
readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 4156
Header {types_: Types, protocol_: "SMB", command_: 46, errorClass_: 0, errorCode_: 0}command_: 46errorClass_: 0errorCode_: 0flag2_: 51202flag_: 152multiplexId_: 9ntStyleErrorCode_: 0processId_: 2protocol_: "SMB"treeId_: 1types_: TypesuserId_: 1__proto__: Header
ReadAndxResponse {types_: Types, responseUtils_: ResponseUtils, available_: 0, dataCompactionMode_: 0, dataLength_: 4096}available_: 0dataCompactionMode_: 0dataLength_: 4096data_: Uint8Array[4096]responseUtils_: ResponseUtilstypes_: Types__proto__: ReadAndxResponse
writePacket
readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 288
Header {types_: Types, protocol_: "SMB", command_: 46, errorClass_: 0, errorCode_: 0}command_: 46errorClass_: 0errorCode_: 0flag2_: 51202flag_: 152multiplexId_: 10ntStyleErrorCode_: 0processId_: 2protocol_: "SMB"treeId_: 1types_: TypesuserId_: 1__proto__: Header
ReadAndxResponse {types_: Types, responseUtils_: ResponseUtils, available_: 0, dataCompactionMode_: 0, dataLength_: 228}available_: 0dataCompactionMode_: 0dataLength_: 228data_: Uint8Array[228]responseUtils_: ResponseUtilstypes_: Types__proto__: ReadAndxResponse
writePacket
readPacket
_readPacketSize
Looked up with chrome.mdns:  [Object, Object, Object, Object, Object, Object, Object]
Looked up with chrome.mdns:  [Object, Object, Object, Object, Object, Object, Object, Object]
```

**Comment by smbuser** [comment]
Hello -

I have this same problem with access to network shares. Error  + STATUS_BUFFER_OVERFLOW 0x80000005.

**Comment by smbuser** [comment]
Hello again
I made some investigations about this issue. When file server has more than five shares and a few printers it's immpossible to connect. I think it depends on number of character used in the names of shares. When I use single letter in share name I can connect to the server which shares more than five directories. So, I think in version 1.4.6 there is a bug whcich depends on number of characters or number on shares. Could you answer me when will you fix this problem ?

**Comment by smbuser** [comment]
Hello..
Today I made next tests on server with Windows server 2008R2 and active directory domain. For the first step, I shared this folders:

shared folder 1
shared folder 2
test 1
test 2
test 3

![screenshot 2015-08-05 at 08 29 17](https://cloud.githubusercontent.com/assets/13346531/9079768/e53e0b5c-3b4d-11e5-9813-d9ef6ce10e1a.png)

In the next step, I added "test 4". After that, connection was impossible. I received "attempting to mount" and nothing happens.

When I changed the names of first and second shares to s1 and s2 the connection could be possible again.

![screenshot 2015-08-05 at 08 32 12](https://cloud.githubusercontent.com/assets/13346531/9079751/c8bb39aa-3b4d-11e5-9d30-8e96724e36fc.png)

On this serwer, there are 3 printers. So, I think the $prints is not necessary to be shown.
As I said, I think that many number of characters in the names and maybe printers cause that I can not mount shares.
On the other server, It's possible to mount 8 shares with longer names, but without any printers. So the problems with configuration, security or network are excluded.

**Comment by smbuser** [comment]
I found solution why I don't have access to network shares. In version 1.4.3  applications yoichiro fixed problems with buffer size  - change value 1024 to 1024 \* 8. In version 1.4.5 and 1.4.6 yoichiro declare variable -  Constants.TRANSACTION_BUFFER_SIZE = 1024. Yoichiro forgot change to value 1024 as 1024 \* 8 so when I changed this  Constants.TRANSACTION_BUFFER_SIZE = 1024 \* 8 ;I build application again, I have access to network shares now.

For our purpose unfortunatelly it's not enough. One of our server has a 93 shares and 6 printers ! So, I increased this value to 1024 \* 32, but it's still to low I think. When I increased this value more, the app could not connect anymore. I don't know why, but the maximum value is only 1024*32

**Comment by yoichiro** [comment]
@smbuser Hmm... I'm confusing why my app could not continue to get your shared resource list from your server. Basically, I modified the constant value from 1024 \* 8 to 1024, because I changed the logic so that my app can get the shared resource list repeatedly. For instance, when a server returns the STATUS_BUFFER_OVERFLOW value, my app sends a SMB_COM_READ_ANDX request to the server for getting the remaining list. That is, from 1.4.6, I think that my app can get the shared resource list by using multiple requests.

As the result, the way to increase the buffer size does not become a solution to fix the issue which my app cannot get a large resource list, I think.

Could you report the debug log on the console tab of DevTools by the following steps, when you face this issue?
https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by smbuser** [comment]
Hello again

**Below Debug log  -  second file server - 93 shares and 6 printers**

_connect
Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
NegotiateProtocolRequest {types_: Types, dialects: Array[0], dialects_: Array[1]}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 47}
CAP_EXTENDED_SECURITY: true
CAP_COMPRESSED_DATA: false
CAP_BULK_TRANSFER: false
CAP_UNIX: false
CAP_LARGE_WRITEX: true
CAP_LARGE_READX: true
CAP_INFOLEVEL_PASSTHROUGH: true
CAP_DFS: false
CAP_NT_FIND: true
CAP_LOCK_AND_READ: true
CAP_LEVEL_II_OPLOCKS: true
CAP_STATUS32: true
CAP_RPC_REMOTE_APIS: true
CAP_NT_SMBS: true
CAP_LARGE_FILES: true
CAP_UNICODE: true
CAP_MPX_MODE: false
CAP_RAW_MODE: false
NEGOTIATE_SECURITY_SIGNATURES_REQUIRED: 0
NEGOTIATE_SECURITY_SIGNATURES_ENABLED: 0
NEGOTIATE_SECURITY_CHALLENGE_RESPONSE: 1
NEGOTIATE_SECURITY_USER_LEVEL: 1
Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
NegotiateProtocolResponse {types_: Types, dialectIndex_: 0, securityMode_: 3, maxMpxCount_: 50, maxNumberVCs_: 1…}
Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 0, errorCode_: 0…}
SessionSetupAndxRequest {types_: Types, maxBufferSize_: 16644, maxMpxCount_: 50, vcNumber_: 1, sessionKey_: 0…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 160}
Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 22, errorCode_: 49152…}
NTLMSSP_NEGOTIATE_UNICODE: true
NTLMSSP_NEGOTIATE_OEM: false
NTLMSSP_REQUEST_TARGET: true
NTLMSSP_NEGOTIATE_SIGN: false
NTLMSSP_NEGOTIATE_SEAL: false
NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
NTLMSSP_NEGOTIATE_LM_KEY: false
NTLMSSP_NEGOTIATE_NETWARE: false
NTLMSSP_NEGOTIATE_NTLM: true
NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
NTLMSSP_NEGOTIATE_LOCAL_CALL: false
NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
NTLMSSP_TARGET_TYPE_DOMAIN: true
NTLMSSP_TARGET_TYPE_SERVER: false
NTLMSSP_TARGET_TYPE_SHARE: false
NTLMSSP_NEGOTIATE_NTLM2: true
NTLMSSP_REQUEST_INIT_RESPONSE: false
NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
NTLMSSP_NEGOTIATE_TARGET_INFO: true
NTLMSSP_NEGOTIATE_128: true
NTLMSSP_NEGOTIATE_KEY_EXCH: false
NTLMSSP_NEGOTIATE_56: false
Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 0, errorCode_: 0…}
SessionSetupAndxRequest {types_: Types, maxBufferSize_: 16644, maxMpxCount_: 50, vcNumber_: 1, sessionKey_: 0…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 494}
Header {types_: Types, protocol_: "SMB", command_: 117, errorClass_: 0, errorCode_: 0…}
TreeConnectAndxRequest {types_: Types, path_: "\scuw\IPC$", service_: "?????"}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 74}
Header {types_: Types, protocol_: "SMB", command_: 117, errorClass_: 0, errorCode_: 0…}
TreeConnectAndxResponse {types_: Types, responseUtils_: ResponseUtils, supportSearchBits_: true, shareIsInDfs_: false, service_: "IPC"}
Header {types_: Types, protocol_: "SMB", command_: 162, errorClass_: 0, errorCode_: 0…}
NtCreateAndxRequest {types_: Types, flags_: 22, rootDirectoryFId: 0, desiredAccess_: 131487, allocationSize_: 0…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 100}
Header {types_: Types, protocol_: "SMB", command_: 162, errorClass_: 0, errorCode_: 0…}
NtCreateAndxResponse {types_: Types, responseUtils_: ResponseUtils, opLockLevel_: 0, fid: null, createDisposition_: 1…}
Header {types_: Types, protocol_: "SMB", command_: 37, errorClass_: 0, errorCode_: 0…}
TransactionRequest {types_: Types, transactionName_: "\PIPE\", flags_: 0, timeout_: 0, parameter_: null…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 154}
Header {types_: Types, protocol_: "SMB", command_: 37, errorClass_: 0, errorCode_: 0…}
DceRpcBindAck {types_: Types, dceRpc_: DceRpc, ackResult_: 0}
Header {types_: Types, protocol_: "SMB", command_: 37, errorClass_: 0, errorCode_: 0…}
TransactionRequest {types_: Types, transactionName_: "\PIPE\", flags_: 0, timeout_: 0, parameter_: null…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 166}
Header {types_: Types, protocol_: "SMB", command_: 37, errorClass_: 5, errorCode_: 32768…}
Header {types_: Types, protocol_: "SMB", command_: 46, errorClass_: 0, errorCode_: 0…}
ReadAndxRequest {types_: Types, requestUtils_: RequestUtils, fid_: 3, offset_: 0, length_: 57344}
Header {types_: Types, protocol_: "SMB", command_: 46, errorClass_: 0, errorCode_: 0…}
ReadAndxResponse {types_: Types, responseUtils_: ResponseUtils, available_: 0, dataCompactionMode_: 0, dataLength_: 3256…}
Header {types_: Types, protocol_: "SMB", command_: 46, errorClass_: 0, errorCode_: 0…}
ReadAndxRequest {types_: Types, requestUtils_: RequestUtils, fid_: 3, offset_: 3256, length_: 57344}
Header {types_: Types, protocol_: "SMB", command_: 46, errorClass_: 0, errorCode_: 0…}
ReadAndxResponse {types_: Types, responseUtils_: ResponseUtils, available_: 0, dataCompactionMode_: 0, dataLength_: 4280…}
Header {types_: Types, protocol_: "SMB", command_: 46, errorClass_: 0, errorCode_: 0…}
ReadAndxRequest {types_: Types, requestUtils_: RequestUtils, fid_: 3, offset_: 7536, length_: 57344}
Header {types_: Types, protocol_: "SMB", command_: 46, errorClass_: 0, errorCode_: 0…}
ReadAndxResponse {types_: Types, responseUtils_: ResponseUtils, available_: 0, dataCompactionMode_: 0, dataLength_: 2400…}
Header {types_: Types, protocol_: "SMB", command_: 46, errorClass_: 0, errorCode_: 0…}
ReadAndxRequest {types_: Types, requestUtils_: RequestUtils, fid_: 3, offset_: 9936, length_: 55599}_

In version 1.5.0 application I have access to my first file server when the shared resource name as "home", but i have problems with my home directory - "\home\fkonwinm", If shared resource name as "fkonwinm"  or "\home\fkonwinm" application gives me error message NT_STATUS_BAD_NETWORK_NAME

**Debug log  -  first file server - shared resource name as "fkonwinm"**

_connect
Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
NegotiateProtocolRequest {types_: Types, dialects: Array[0], dialects_: Array[1]}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 47}
CAP_EXTENDED_SECURITY: true
CAP_COMPRESSED_DATA: false
CAP_BULK_TRANSFER: false
CAP_UNIX: false
CAP_LARGE_WRITEX: true
CAP_LARGE_READX: true
CAP_INFOLEVEL_PASSTHROUGH: true
CAP_DFS: true
CAP_NT_FIND: true
CAP_LOCK_AND_READ: true
CAP_LEVEL_II_OPLOCKS: true
CAP_STATUS32: true
CAP_RPC_REMOTE_APIS: true
CAP_NT_SMBS: true
CAP_LARGE_FILES: true
CAP_UNICODE: true
CAP_MPX_MODE: false
CAP_RAW_MODE: true
NEGOTIATE_SECURITY_SIGNATURES_REQUIRED: 0
NEGOTIATE_SECURITY_SIGNATURES_ENABLED: 0
NEGOTIATE_SECURITY_CHALLENGE_RESPONSE: 1
NEGOTIATE_SECURITY_USER_LEVEL: 1
Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
NegotiateProtocolResponse {types_: Types, dialectIndex_: 0, securityMode_: 3, maxMpxCount_: 50, maxNumberVCs_: 1…}
Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 0, errorCode_: 0…}
SessionSetupAndxRequest {types_: Types, maxBufferSize_: 16644, maxMpxCount_: 50, vcNumber_: 1, sessionKey_: 0…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 160}
Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 22, errorCode_: 49152…}
NTLMSSP_NEGOTIATE_UNICODE: true
NTLMSSP_NEGOTIATE_OEM: false
NTLMSSP_REQUEST_TARGET: true
NTLMSSP_NEGOTIATE_SIGN: false
NTLMSSP_NEGOTIATE_SEAL: false
NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
NTLMSSP_NEGOTIATE_LM_KEY: false
NTLMSSP_NEGOTIATE_NETWARE: false
NTLMSSP_NEGOTIATE_NTLM: true
NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
NTLMSSP_NEGOTIATE_LOCAL_CALL: false
NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
NTLMSSP_TARGET_TYPE_DOMAIN: true
NTLMSSP_TARGET_TYPE_SERVER: false
NTLMSSP_TARGET_TYPE_SHARE: false
NTLMSSP_NEGOTIATE_NTLM2: true
NTLMSSP_REQUEST_INIT_RESPONSE: false
NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
NTLMSSP_NEGOTIATE_TARGET_INFO: true
NTLMSSP_NEGOTIATE_128: true
NTLMSSP_NEGOTIATE_KEY_EXCH: false
NTLMSSP_NEGOTIATE_56: false
Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 0, errorCode_: 0…}
SessionSetupAndxRequest {types_: Types, maxBufferSize_: 16644, maxMpxCount_: 50, vcNumber_: 1, sessionKey_: 0…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 502}
Header {types_: Types, protocol_: "SMB", command_: 117, errorClass_: 0, errorCode_: 0…}
TreeConnectAndxRequest {types_: Types, path_: "\cl-dc0001\FKONWINM", service_: "?????"}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 92}_

**Debug log  -  first file server - shared resource name as "home\fkonwinm"**

_connect
Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
NegotiateProtocolRequest {types_: Types, dialects: Array[0], dialects_: Array[1]}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 47}
CAP_EXTENDED_SECURITY: true
CAP_COMPRESSED_DATA: false
CAP_BULK_TRANSFER: false
CAP_UNIX: false
CAP_LARGE_WRITEX: true
CAP_LARGE_READX: true
CAP_INFOLEVEL_PASSTHROUGH: true
CAP_DFS: true
CAP_NT_FIND: true
CAP_LOCK_AND_READ: true
CAP_LEVEL_II_OPLOCKS: true
CAP_STATUS32: true
CAP_RPC_REMOTE_APIS: true
CAP_NT_SMBS: true
CAP_LARGE_FILES: true
CAP_UNICODE: true
CAP_MPX_MODE: false
CAP_RAW_MODE: true
NEGOTIATE_SECURITY_SIGNATURES_REQUIRED: 0
NEGOTIATE_SECURITY_SIGNATURES_ENABLED: 0
NEGOTIATE_SECURITY_CHALLENGE_RESPONSE: 1
NEGOTIATE_SECURITY_USER_LEVEL: 1
Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
NegotiateProtocolResponse {types_: Types, dialectIndex_: 0, securityMode_: 3, maxMpxCount_: 50, maxNumberVCs_: 1…}
Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 0, errorCode_: 0…}
SessionSetupAndxRequest {types_: Types, maxBufferSize_: 16644, maxMpxCount_: 50, vcNumber_: 1, sessionKey_: 0…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 160}
Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 22, errorCode_: 49152…}
NTLMSSP_NEGOTIATE_UNICODE: true
NTLMSSP_NEGOTIATE_OEM: false
NTLMSSP_REQUEST_TARGET: true
NTLMSSP_NEGOTIATE_SIGN: false
NTLMSSP_NEGOTIATE_SEAL: false
NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
NTLMSSP_NEGOTIATE_LM_KEY: false
NTLMSSP_NEGOTIATE_NETWARE: false
NTLMSSP_NEGOTIATE_NTLM: true
NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
NTLMSSP_NEGOTIATE_LOCAL_CALL: false
NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
NTLMSSP_TARGET_TYPE_DOMAIN: true
NTLMSSP_TARGET_TYPE_SERVER: false
NTLMSSP_TARGET_TYPE_SHARE: false
NTLMSSP_NEGOTIATE_NTLM2: true
NTLMSSP_REQUEST_INIT_RESPONSE: false
NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
NTLMSSP_NEGOTIATE_TARGET_INFO: true
NTLMSSP_NEGOTIATE_128: true
NTLMSSP_NEGOTIATE_KEY_EXCH: false
NTLMSSP_NEGOTIATE_56: false
Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 0, errorCode_: 0…}
SessionSetupAndxRequest {types_: Types, maxBufferSize_: 16644, maxMpxCount_: 50, vcNumber_: 1, sessionKey_: 0…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 502}
Header {types_: Types, protocol_: "SMB", command_: 117, errorClass_: 0, errorCode_: 0…}
TreeConnectAndxRequest {types_: Types, path_: "\cl-dc0001\HOME\FKONWINM", service_: "?????"}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 102}_

**Comment by yoichiro** [comment]
@smbuser At least, your log doesn't have any error messages. I cannot find a reason. You should report ALL log outputs.

**Comment by smbuser** [comment]
@yoichiro In console i don't have any errors 

second file server - 93 shares and 6 printers - working in version 1.5.0 when I specify shared resource names

**Comment by yoichiro** [comment]
@smbuser Hmm... I think I will not be able to fix your issue, because I cannot reproduce your situation...

**Comment by smbuser** [comment]
@yoichiro I have only this error 

![screenshot 2015-08-10 at 13 03 46](https://cloud.githubusercontent.com/assets/13346531/9170127/77e09f72-3f60-11e5-8c3f-1d4f86510f1e.png)

**Comment by yoichiro** [comment]
@smbuser Thanks, smbuser, OK, I have some questions. Is the server name "cl-dc0001" correct full name? Or, is the name actually NetBIOS name? Or, correctly, is the server name "cl-dc0001.domain.name"? And, probably, I guess that you should enter "fkowimm" as the shared resource name, instead of "home/***". Could you re-post a screenshot when you try to enter "fkowimm" only?

**Comment by smbuser** [comment]
Hello @yoichiro 

server name cl-dc0001 and cl-dc0001.domain.name is correct

\cl-dc0001\home\fkonwinm - this is my home directory

when I enter only fkonwinm as shared resource name I have this same error

![screenshot 2015-08-11 at 07 09 26](https://cloud.githubusercontent.com/assets/13346531/9190657/0b8e865c-3ff8-11e5-8018-7b4de8cf4fea.png)

**Comment by yoichiro** [comment]
@smbuser Does your account have a permission to read the shared resource? See: http://serverfault.com/questions/137135/what-does-nt-status-bad-network-name-mean-in-samba

**Comment by smbuser** [comment]
Hello,
@yoichiro I have a two questions. 
1. Which your folder is shared - home or yoichiro because in my company folder home is a share ,not my folder fkonwinm and when shared is fkonwinm and share resource name is fkonwinm  then I get access 
2. When i have mounted two different shares from one serwer how I can keep their settings?

**Comment by yoichiro** [comment]
@smbuser I could reproduce the error message "BAD_NETWORK_NAME", when I tried to connect to my home directory. I intend to investigate this issue soon.

**Comment by yoichiro** [comment]
@smbuser I investigated the error message. I tried to mount my user account which doesn't have any home directory to my Samba server, I could reproduce the error message (BAD_NETWORK_NAME). At the time, the Samba log file had the following line:

[2015/09/04 06:08:31.880117,  0] smbd/service.c:1092(make_connection_snum)
  '/nonexistent' does not exist or permission denied when connecting to [yoichiro] Error was No such file or directory

Actually, the user account doesn't have any home directory. Instead, the path "/nonexistent" is set. This is a default setting in FreeNAS server.

Next, I tried to mount another user account which has a existing home directory to other Samba server. Of course, I could mount it.

As the result, I believe that this problem caused by your server setting, didn't cause by my app. I think that you should confirm your server setting. Thanks.
