### ISSUE TITLE
Simple windows share via linksys wireless AP

### ISSUE THREAD

**Issue by hydrokracker** [yoichiro/chromeos-filesystem-cifs#79]
I have a linksys router which mounts the USB port connection as a windows share. I can access it from every device including my chromebox (when running ubuntu).  I receive "ERR_NAME_NOT_RESOLVED" when attemping with this tool

Ip address:

smb://192.168.1.1/Network Storage/
Port: 445
user, password: Anonymous
domain name: empty

**Comment by hydrokracker** [comment]
when attempting to connect using \192.168.1.1 instead the application says attempting to mount instance but then times out. "net:ERR_CONNECTION_TIME_OUT"

to be clear these are the Error messages I am receiving from both my Asus C200MA and M004U both stock Chrome OS. (when running the M004U in Ubuntu SMB works just fine)

**Comment by yoichiro** [comment]
@hydrokracker Could you check a debug log output on the console tab of the DevTools by using the steps? https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by yoichiro** [comment]
I close this issue, because the reporter could not post more information here. Sorry.
