### ISSUE TITLE
Can n't unmount SMB folder from File Manager.

### ISSUE THREAD

**Issue by AndreyLavrov** [yoichiro/chromeos-filesystem-cifs#8]
New folder was not registered in SMB app after creation but this folder still present in the File Manager.
I can not unmount this folder from File Manager.
![screenshot 2015-06-02 at 11 25 43](https://cloud.githubusercontent.com/assets/12710354/7931629/d871d314-091a-11e5-91d6-9803fb974ac0.png)

**Comment by yoichiro** [comment]
@AndreyLavrov Could you confirm the debug console output? Probably, some error occurrd at the time, I guess. You can confirm the output by the following steps:
https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by AndreyLavrov** [comment]
The following steps are reproducing issue:
1) Install SMB/CIFS app
2) Starting the app
3) Change settings: Keep password = "Yes"
4) Setting values for IP Address, Port, User Name, Password then press "KEEP"
5) Press "Mount"
After step 5 a string for SMB folder was appeared in File Manager but all activity in an activity tracer and a console were stopped.
All other folders in File Manager works fine until you press on SMB folder. After that file list in File Manager can not be changed even if you click any folders. However if you click on files in the a "frozen" file list then application can launch yet.
![smb trace](https://cloud.githubusercontent.com/assets/12710354/7986178/837db4a2-0ade-11e5-86ee-b8c3151cf577.png)

**Comment by yoichiro** [comment]
@AndreyLavrov Hmm... Any errors not found in the output above... Sorry, I can't understand the situation... Well, in the next version, I intend to add a new UI to turn on the debug mode.

**Comment by AndreyLavrov** [comment]
I have tried to trace SMB app as well as Files app and see no exceptions but one that is described below:
When I clicked to a "mounted" folder in the Files app then exception is fired exactly at the moment of swapping extension handler to Image Loader in the Files app. This exception is suppressed by Files app by a catch and have no console log but new handler for loader is undefined. May be problem there? May be I have no such hidden extension in my stable release?
Can you list here all extension IDs (with their names) that are reqired for SMB app? I will try to check all dependencies on my Chrome OS (43.0.2357.81 (64-bit)).

**Comment by yoichiro** [comment]
@AndreyLavrov Hmm... My SMB app has no dependent other apps/extensions... You should understand it by looking at the manifest.json file: https://github.com/yoichiro/chromeos-filesystem-cifs/blob/master/app/manifest.json

**Comment by yoichiro** [comment]
@AndreyLavrov Probably, I could reproduce your situation. I just released a new version 1.1.8. Could you confirm whether the new version works on your environment?

**Comment by AndreyLavrov** [comment]
SMB ver. 1.1.8 have solved the issue!
Now I can unmount SMB shares on Windows 7 (Standalone) and Windows 2008 R2 (Member).
P.S. When I unmount SMB folder there are no errors in Files.app but there is same console output for SMB's background.js (see picture below). All mounting/unmounting procedures are working well for Windows  7 / Windows 2008 R2 folders. I think that issue could be closed.
![smb unmount](https://cloud.githubusercontent.com/assets/12710354/8056051/432346ec-0ead-11e5-9516-3c197b9da0ba.png)

**Comment by yoichiro** [comment]
@AndreyLavrov Good. :)
