### ISSUE TITLE
Samba browse not listing users home folder?

### ISSUE THREAD

**Issue by unixabg** [yoichiro/chromeos-filesystem-cifs#82]
Greetings,

I have many shares on a samba server. The extension is not showing the logged in users home folder in the list of available shares. This may be a samba issue or it may need to refresh the listing screen. Any ideas?  Also how do I refresh the listing of available shares from the samba server?

Thanks.

**Comment by yoichiro** [comment]
@unixabg Could you check the configuration of the user home directory in the smb.conf? I guess that the configuratoin has "browsable = no"...

**Comment by unixabg** [comment]
Greetings,

Yes I believe you are correct and I furthermore believe the samba default (for home folders) appears to be "browseable = no".  Is there a way I can specify the UNC path to my home folder?

Thanks.

**Comment by yoichiro** [comment]
@unixabg I have released a new version 1.5.0 yesterday. This version has a new text field to enter a shared resource name you want to mount. For example, if I have a home directory "/home/yoichiro", I should be able to mount my home directory by specifying the shared resource name as "yoichiro". Could you try this new feature on your environment?

**Comment by unixabg** [comment]
Greetings,

Share mounted and all seems to work perfect! 

yoichiro++

On a minor side note, I think it would be nice to see the version number  (1.5.0 in this case) of the extension at the bottom right.

Thanks for the great tool!

**Comment by yoichiro** [comment]
@unixabg My pleasure. Thank you for your feedback. :) OK, I intend to add the version number label on the bottom right of the screen.
