### ISSUE TITLE
trying to access shared folders off windows 2008 server

### ISSUE THREAD

**Issue by chains36** [yoichiro/chromeos-filesystem-cifs#83]
I was able to mount my drives at home off my windows 7 server. I brought into my office and I am getting time out errors. What's going on?

**Comment by chains36** [comment]
Now I'm getting access denied 3221225506

**Comment by unixabg** [comment]
Greetings,

Could you please provide more detailed information about the network share server you are attempting to connect which is causing the issue?

Thanks.

**Comment by chains36** [comment]
Windows 2008 server. Trying to access the shared directories on the local network. Its a pretty basic network. Does this help?

Nicko Sarris

**Comment by yoichiro** [comment]
@chains36 Could you check whether your Windows 2008 server records some errors?

**Comment by chains36** [comment]
nt status logon failure. This is the error message I am receiving now.

**Comment by yoichiro** [comment]
@chains36 Can your server accept NTLMv2 and LMv2 user authentication method? Or, Is your server joining to certain domain provided by NT server or ActiveDirectory?

**Comment by chains36** [comment]
I'm assuming it can. It's all default settings. All other computers can access the shared directories on the server.  This is not on a domain with active directory. 

I am also not able to access a windows 7 computer with a shared directory. 

Nicko Sarris

**Comment by chains36** [comment]
This HP chromebox is useless without smb to access a shared directory on the network.

**Comment by yoichiro** [comment]
@chains36 Could you post the debug log here by the following steps with the latest version?
https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by yoichiro** [comment]
@chains36 I close this issue, because you didn't provide a log...
