### ISSUE TITLE
How do I remove a mounted share?

### ISSUE THREAD

**Issue by etuck** [yoichiro/chromeos-filesystem-cifs#84]
Thanks for building the app.  I've been waiting for a way to use SMB shares on my Chromebook for some time now.

One question: how can I remove mounted shares once they are created?  I don't see any way to do that in the SMB app or File Manager.  The share seems to be working fine but I'm constantly getting errors from it.  Mostly "Some operations are taking longer than expected..."

Thanks.

**Comment by yoichiro** [comment]
@etuck Could you find a "Close" menu item when you right-click the shared name on the Files app?

**Comment by yoichiro** [comment]
I close this issue, because I could not get more information from the reporter. Sorry.
