### ISSUE TITLE
SMB cannot refresh current folder

### ISSUE THREAD

**Issue by AndreyLavrov** [yoichiro/chromeos-filesystem-cifs#85]
SMB app cannot refresh current folder after the folder was updated by other user.

Steps to reproduce issue:
1) Install SMB app and mount shared folder from Windows Server under domain user account.
2) Create, update, delete files in the folder from other computers.
3) SMB app still showing deleted files, old size from updated files and it does not show new files.
![smb refresh](https://cloud.githubusercontent.com/assets/12710354/9153840/610056f2-3e7b-11e5-8bb1-0e3c7012f08d.png)

**Comment by yoichiro** [comment]
@AndreyLavrov Recently, FSP API has been updated. A new events and functions were added to notify a file list from an app to ChromeOS automatically, I guess. I intend to implement an auto-refresh feature with the events and functions.

**Comment by yoichiro** [comment]
@AndreyLavrov I will release an auto-refresh feature with a watcher event after releasing ChromeOS 45 stable. I already created a code to do it. #89

**Comment by yoichiro** [comment]
@AndreyLavrov I released a new version 2.0.0 including the auto-updating feature of a file list. The file list will be updated per a minute automatically. I close this issue.
