### ISSUE TITLE
Nothing happens after installing on M44.

### ISSUE THREAD

**Issue by mtomasz-chromium** [yoichiro/chromeos-filesystem-cifs#9]
M44 is hitting beta soon, and onLaunched is not dispatched automatically when an app/extension is installed. I'd recommend to add listeners to onMountRequested and onConfigureRequested.

To maintain backward compatibility with M42 and M43 you can do:
if (chrome.fileSystemProvider.onMountRequested) {
  chrome.fileSystemProvider.onMountRequested.addListener(...);
}

**Comment by yoichiro** [comment]
Thank you for this reporting. The new version already released. #11
