### ISSUE TITLE
Error when trying to write to router drive

### ISSUE THREAD

**Issue by kahar9** [yoichiro/chromeos-filesystem-cifs#92]
I can read files fine on my routers internal and usb hard drive, however when every try to write files anywhere I get an error. The router is a WD My Net Central N900 by the way. I can read/write fine on my Windows PC but not my Chromebook. Thanks
![screenshot 2015-08-14 at 02 33 37](https://cloud.githubusercontent.com/assets/13790267/9265601/912c63c4-422d-11e5-8424-1721d4f09631.png)

**Comment by yoichiro** [comment]
@kahar9 When you faced this issue, could you check an output log for debugging on a DevTools Console tab with the following steps, and post it as a comment here?
https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by yoichiro** [comment]
I close this issue, because I could not get more information from the reporter. Sorry.
