### ISSUE TITLE
SMB/CIFS extension has unexpected operation at logon 

### ISSUE THREAD

**Issue by cottonwool** [yoichiro/chromeos-filesystem-cifs#93]
Sometimes when I log on to my Chromebook I see error messages from SMB/CIFS to the effect that it can't connect. 
It can't connect because my PC is switched off and I haven't let SMB/CIFS keep my password.
But I didn't start the extension anyway! And my PC is not accessible when I'm away from my LAN.

I had been using SMB/CIFS successfully the previous time I was logged on. (Though I do seem to need to keep the background window console open to stop it stalling, I will investigate this further and report back.)

I don't normally explicitly close the connection before I log off. I assume this should happen automatically when the Chromebook is logged off.

Could we have the option to control whether or not SMB/CIFS starts up automatically when logging on to the Chromebook?

Is automatic start-up (or resume) of the extension at login supposed to be a feature?

**Comment by yoichiro** [comment]
@cottonwool Hmm... Yes, if you opened a Files app and shutdowned your Chromebook, and when you turn on the chromebook, the ChromeOS will try to re-open the Files app and resume mounting to your server which was connected before shutdown. However, as my experiences, the network interface is not prepared yet... Therefore, my SMB app could not re-connect to your server, and showed an error notification, I guess. Currently, I don't have a nice idea to fix this issue...

**Comment by cottonwool** [comment]
Native SMB support from Chrome OS 71 makes this issue redundant.
