### ISSUE TITLE
System restarts unexpectedly when browsing SMB share from Synology NAS

### ISSUE THREAD

**Issue by hit0wnzzz** [yoichiro/chromeos-filesystem-cifs#94]
I have a Synology  DS1813+ with DSM 5.2-5592 Update 2 and a INTEL Atom D2700.

Whenever I browse it with your plugin, my dell chromebook restartas

CHROME VERSION
46.0.2472.0 dev
CHROMEOS_RELEASE_BUILD_NUMBER
7330

**Comment by yoichiro** [comment]
@hit0wnzzz I don't intend to support the dev channel. Sorry. Actually, I'm developing my apps with a beta channel.
