### ISSUE TITLE
Readyshare

### ISSUE THREAD

**Issue by WillemChromebook** [yoichiro/chromeos-filesystem-cifs#98]
I have a network disk on my netgear router, which is accessible as readyshare. I have not been able to mount it with the chromebook SMB app. I tried
smb://readyshare
smb:\readyshare
smb://readyshare/USB_storage
readyshare
etc., etc.
I have to add that readyshare does not show up under servers, although it does on my MAC and android tablet. Some chromebook setting pronlem?
How should I mount it?

**Comment by yoichiro** [comment]
@WillemChromebook First, I want to know what did you fill in to each field (Server Host Name, Port, User Name, Domain Name and Shared resource name). Or, you can send the screenshot when you fill in to each field here.

**Comment by yoichiro** [comment]
I close this issue, because I could not get more information to fix this issue from the reporter. Sorry.

**Comment by WillemChromebook** [comment]
I was on vacation the last two weeks and I could not send screen shots. I
will do that today.

**Comment by didtoknan** [comment]
Hi,

I want to do the same thing.
My netgear router has a USB port which allows me to share the usb drives I plug to it.
The access point is readyshare.
It works on Windows and Android.

IP Address: 192.168.1.1 (ip of my router)
Server port number: 445 (the default one)
User Name and Password empty 
Domain Name empty
Shared ressource name: readyshare

Please help us !

**Comment by dabend** [comment]
I've had the same problem on a Netgear WNR3500.  The following command will mount the readyshare drive on in Linux (Mint LMDE).  I've also tried a number of combinations including IP and either get a login error or a name resolve error.

fstab:  //197.0.0.1/~shared  /media/gw2kshared  cifs    guest,rw,iocharset=utf8,noserverino,file_mode=0777,dir_mode=0777 0 0

![screenshot 2016-03-31 at 6 57 19 pm](https://cloud.githubusercontent.com/assets/18200399/14194292/8b636082-f772-11e5-9148-a886de8e8acb.png)

![screenshot 2016-03-31 at 7 02 13 pm](https://cloud.githubusercontent.com/assets/18200399/14194352/37600aa2-f773-11e5-9b77-becd9b9ea226.png)

![screenshot 2016-03-31 at 7 04 24 pm](https://cloud.githubusercontent.com/assets/18200399/14194380/7a871fdc-f773-11e5-8118-54eb6ac675e1.png)

**Comment by dboles777** [comment]
When I removed the "Shared Resource Name" I was able to get it to work with the IP address you would use to connect through an FTP or https: using the Server Port Number for the https: address.  Hope it works for you as well.
